// GENERATED from contracts/technical/failures.json by scripts/generate-failures.mjs. Do not edit.

/** What a page the Hub renders itself says for a row that reaches a person: the message, then its action. */
export const FAILURE_TEXT = {
  'INTERNAL_UNEXPECTED': 'O Conexus falhou de um jeito que não esperávamos. A falha foi registrada.',
  'NOT_FOUND': 'Não encontramos o que você procurou.',
  'REQUEST_VALIDATION_FAILED': 'Alguns dados do pedido não são válidos.',
  'REQUEST_JSON_INVALID': 'O pedido chegou ao Conexus ilegível.',
  'REQUEST_BODY_TOO_LARGE': 'O pedido é maior do que o Conexus aceita.',
  'REQUEST_MEDIA_TYPE_UNSUPPORTED': 'O Conexus não aceita esse formato de pedido.',
  'AUTHENTICATION_REQUIRED': 'Você precisa entrar para continuar. Entre na sua conta para continuar.',
  'REQUEST_AUTHENTICITY_DENIED': 'O Conexus não conseguiu confirmar que o pedido veio de você. Recarregue a página.',
  'IDEMPOTENCY_KEY_REQUIRED': 'O pedido saiu sem o identificador que o Conexus exige. A falha foi registrada.',
  'IDEMPOTENCY_CONFLICT': 'Já existe um pedido igual a este, com dados diferentes.',
  'OUTCOME_UNKNOWN': 'O Conexus não conseguiu confirmar se o pedido anterior terminou. A falha foi registrada.',
  'DATABASE_BUSY': 'O Conexus está ocupado e não terminou o pedido. A falha foi registrada.',
  'IDENTITY_PROVIDER_UNAVAILABLE': 'O serviço de login não respondeu agora. Sua sessão continua aberta. Tente novamente mais tarde.',
  'SIGN_IN_EXPIRED': 'O login demorou demais ou foi aberto em outra aba. Entre de novo.',
  'SIGN_IN_FAILED': 'O serviço de login não concluiu a entrada. Entre de novo.',
  'IDENTITY_EMAIL_NOT_VERIFIED': 'O seu provedor de login informou que o e-mail desta conta ainda não foi verificado. Confirme o e-mail no seu provedor de login e entre de novo.',
  'IDENTITY_NOT_ELIGIBLE': 'Você entrou, mas ninguém convidou este e-mail para o Conexus. Peça um convite a quem cuida do seu Workspace, com este mesmo e-mail.',
  'ACCOUNT_INACTIVE': 'Esta conta foi desativada no Conexus. Peça a quem administra o Conexus.',
  'WORKSPACE_NOT_FOUND': 'Não encontramos esse Workspace.',
  'PROJECT_NOT_FOUND': 'Não encontramos esse Projeto.',
  'PROJECT_SOURCE_REFUSED': 'O Conexus não aceitou o código inicial deste Projeto.',
  'PROJECT_REPOSITORY_UNAVAILABLE': 'O Conexus não conseguiu usar o repositório do Projeto. A falha foi registrada.',
  'PROJECT_DELETE_DENIED': 'Só uma pessoa proprietária do Workspace pode excluir este Projeto. Peça a quem pode alterar isso.',
  'PROJECT_DELETING': 'Este Projeto está sendo excluído.',
  'PROJECT_NAME_MISMATCH': 'O nome digitado não é o nome do Projeto. Digite exatamente como aparece.',
  'PROJECT_BUSY': 'O Projeto está processando um pedido agora. Espere terminar.',
  'PROJECT_DELETION_INCOMPLETE': 'A exclusão do Projeto não terminou. O que já foi apagado não volta atrás. A falha foi registrada.',
  'PROJECT_THUMBNAIL_NOT_FOUND': 'Este Projeto ainda não tem miniatura.',
  'BUILDER_SESSION_UNAVAILABLE': 'O Conexus não conseguiu abrir a sessão do Builder. A falha foi registrada.',
  'CONVERSATION_NOT_FOUND': 'Não encontramos essa conversa.',
  'BUILDER_CAPACITY_FULL': 'O Conexus está com muitas execuções abertas agora. Tente novamente mais tarde.',
  'BUILDER_MESSAGE_REFUSED': 'O Conexus não aceitou essa mensagem.',
  'BUILDER_UNAVAILABLE': 'O Builder não está disponível agora. A falha foi registrada.',
  'BUILDER_RUN_NOT_FOUND': 'Não encontramos essa execução.',
  'BUILDER_TRACE_UNAVAILABLE': 'O Conexus não conseguiu carregar o detalhe da execução. A falha foi registrada.',
  'PREVIEW_UNAVAILABLE': 'O Conexus não conseguiu abrir a Prévia. A falha foi registrada.',
  'PREVIEW_SUBJECT_NOT_FOUND': 'Não encontramos o que a Prévia mostraria.',
  'PREVIEW_FORM_REFUSED': 'A Prévia não aceitou esse formulário.',
  'SOURCE_REVISION_NOT_FOUND': 'Não encontramos essa versão do código.',
  'SOURCE_FILE_NOT_FOUND': 'Não encontramos esse arquivo.',
  'BUILDER_SOURCE_UNAVAILABLE': 'O Conexus não conseguiu ler o código do Projeto. A falha foi registrada.',
  'REQUEST_CONTEXT_REFUSED': 'O pedido trouxe um contexto que só o Conexus pode definir.',
  'TOOL_ANSWER_REFUSED': 'Só é possível aprovar ou recusar uma ação pendente do agente.',
  'SESSION_STATE_REFUSED': 'Só o nível de raciocínio pode ser alterado aqui.',
  'BUILDER_SESSION_NOT_FOUND': 'Não encontramos essa sessão do Builder.',
  'CONVERSATION_SESSION_REFUSED': 'A sessão de uma conversa só abre na própria conversa.',
  'CONVERSATION_CONFLICT': 'Esse identificador de conversa já está em uso.',
  'BUILDER_BUSY': 'O modelo só muda quando o Builder está parado.',
  'BUILDER_RUN_STOP_REFUSED': 'Uma execução só para pelo botão de parar.',
  'TOOL_ANSWER_ALREADY_GIVEN': 'Esta pergunta já foi respondida.',
  'QUESTION_ENDED': 'Esta pergunta já foi encerrada. A resposta pode ir na próxima mensagem.',
  'APPLICATION_ACCESS_MANAGE_REQUIRED': 'Você não tem permissão para gerenciar quem acessa este aplicativo. Peça a quem administra o Conexus.',
  'APPLICATION_ACCESS_ENTRY_NOT_FOUND': 'Não encontramos esse acesso ao aplicativo.',
  'MEMBERS_MANAGE_REQUIRED': 'Você não tem permissão para gerenciar as pessoas deste Workspace. Peça a quem administra o Conexus.',
  'LAST_OWNER': 'O Workspace ficaria sem dono. Torne outra pessoa dona antes.',
  'ROSTER_ENTRY_NOT_FOUND': 'Não encontramos essa pessoa na lista.',
  'INSTALLATION_ADMINISTRATOR_REQUIRED': 'Só quem administra o Conexus pode fazer isso. Peça a quem administra o Conexus.',
  'EMAIL_INVALID': 'Esse e-mail não é válido.',
  'ACCOUNT_NOT_FOUND': 'Nenhuma conta ativa usa este e-mail. A pessoa precisa entrar no Conexus uma vez antes.',
  'ACCOUNT_EMAIL_AMBIGUOUS': 'Mais de uma conta usa este e-mail. Fale com quem opera o Conexus. Peça a quem administra o Conexus.',
  'INSTALLATION_ADMINISTRATOR_NOT_FOUND': 'Essa pessoa não administra o Conexus.',
  'LAST_INSTALLATION_ADMINISTRATOR': 'Não é possível revogar o último administrador. Torne outra pessoa administradora antes.',
  'CONNECTOR_CONNECTION_NOT_AVAILABLE': 'Esta conexão não está disponível para o Projeto.',
  'CONNECTOR_BINDING_CONFLICT': 'Este nome já está em uso neste Projeto, ou esta conexão já está vinculada com outro nome.',
  'CONNECTOR_BINDING_MANAGE_REQUIRED': 'Você não tem permissão para gerenciar as conexões deste Projeto. Peça a quem administra o Conexus.',
  'CONNECTOR_LABEL_REFUSED': 'O Conexus não aceitou esse nome para a conexão.',
  'CONNECTOR_CREDENTIAL_REFUSED': 'O Conexus não aceitou essas credenciais.',
  'CONNECTOR_CONNECTION_CONFLICT': 'Já existe uma conexão com esses dados.',
  'CONNECTOR_CONNECTION_NOT_FOUND': 'Não encontramos essa conexão.',
  'CONNECTOR_BINDING_NOT_FOUND': 'Não encontramos essa ligação do Projeto com a conexão.',
  'MODEL_ACCOUNT_PROVIDER_UNKNOWN': 'Este provedor não aceita chave de API.',
  'MODEL_ACCOUNT_KEY_REFUSED': 'Essa não é uma chave de API deste provedor.',
  'MODEL_LOGIN_UNAVAILABLE': 'A entrada na conta do modelo não está disponível agora. Tente novamente mais tarde.',
  'MODEL_LOGIN_BUSY': 'Outra entrada na conta do modelo está em andamento. Tente novamente mais tarde.',
  'MODEL_LOGIN_CALLBACK_REFUSED': 'O Conexus não aceitou esse endereço de retorno da entrada.',
  'MODEL_LOGIN_NOT_FOUND': 'Não encontramos essa entrada na conta do modelo.',
  'HUB_UNREACHABLE': 'A tela não conseguiu falar com o Conexus agora. Tente novamente mais tarde.',
  'HUB_RESPONSE_UNREADABLE': 'A resposta que chegou à tela não veio do Conexus. Tente novamente mais tarde.',
  'ANTHROPIC_STORED_RECORD_REFUSED': 'O Conexus não conseguiu ler a credencial salva desta conta de modelo. Conecte uma conta de modelo em Configurações.',
  'APPLICATION_ARTIFACT_INPUT_REFUSED': 'O Conexus não conseguiu guardar o aplicativo compilado. A falha foi registrada.',
  'APPLICATION_CHECK_REPORT_UNREADABLE': 'O Conexus não conseguiu preparar o ambiente de código. A falha foi registrada.',
  'APPLICATION_CHECK_TIMEOUT': 'O Conexus não conseguiu preparar o ambiente de código. A falha foi registrada.',
  'APPLICATION_CHECK_UNREADABLE': 'O Conexus não conseguiu preparar o ambiente de código. A falha foi registrada.',
  'APPLICATION_COMPILER_OUTPUT_ENTRYPOINT_REFUSED': 'Os arquivos do aplicativo têm um formato que o Conexus não aceita. Peça o ajuste ao Builder, na conversa.',
  'APPLICATION_COMPILER_OUTPUT_LIMIT_REFUSED': 'O aplicativo passou do tamanho que o Conexus aceita. Peça o ajuste ao Builder, na conversa.',
  'APPLICATION_COMPILER_OUTPUT_MEDIA_TYPE_REFUSED': 'Os arquivos do aplicativo têm um formato que o Conexus não aceita. Peça o ajuste ao Builder, na conversa.',
  'APPLICATION_COMPILER_OUTPUT_PATH_REFUSED': 'Os arquivos do aplicativo têm um formato que o Conexus não aceita. Peça o ajuste ao Builder, na conversa.',
  'APPLICATION_COMPILER_OUTPUT_SIZE_REFUSED': 'O aplicativo passou do tamanho que o Conexus aceita. Peça o ajuste ao Builder, na conversa.',
  'APPLICATION_COMPILER_WORKSPACE_REFUSED': 'O Conexus não conseguiu preparar o ambiente de código. A falha foi registrada.',
  'APPLICATION_ENTRYPOINT_REFUSED': 'Os arquivos do aplicativo têm um formato que o Conexus não aceita. Peça o ajuste ao Builder, na conversa.',
  'APPLICATION_FILE_COUNT_REFUSED': 'O aplicativo passou do tamanho que o Conexus aceita. Peça o ajuste ao Builder, na conversa.',
  'APPLICATION_FILE_DUPLICATE_REFUSED': 'Os arquivos do aplicativo não passaram na verificação de integridade. Peça o ajuste ao Builder, na conversa.',
  'APPLICATION_FILE_ENCODING_REFUSED': 'Os arquivos do aplicativo não passaram na verificação de integridade. Peça o ajuste ao Builder, na conversa.',
  'APPLICATION_FILE_HASH_REFUSED': 'Os arquivos do aplicativo não passaram na verificação de integridade. Peça o ajuste ao Builder, na conversa.',
  'APPLICATION_FILE_ORDER_REFUSED': 'Os arquivos do aplicativo não passaram na verificação de integridade. Peça o ajuste ao Builder, na conversa.',
  'APPLICATION_FILE_PATH_REFUSED': 'Os arquivos do aplicativo têm um formato que o Conexus não aceita. Peça o ajuste ao Builder, na conversa.',
  'APPLICATION_FILE_SHAPE_REFUSED': 'Os arquivos do aplicativo não passaram na verificação de integridade. Peça o ajuste ao Builder, na conversa.',
  'APPLICATION_FILE_SIZE_REFUSED': 'O aplicativo passou do tamanho que o Conexus aceita. Peça o ajuste ao Builder, na conversa.',
  'APPLICATION_MEDIA_TYPE_REFUSED': 'Os arquivos do aplicativo têm um formato que o Conexus não aceita. Peça o ajuste ao Builder, na conversa.',
  'APPLICATION_MIGRATION_FAILED': 'A mudança nos dados do aplicativo não foi aplicada. Peça o ajuste ao Builder, na conversa.',
  'APPLICATION_MIGRATION_HISTORY_DIVERGED': 'As mudanças nos dados do aplicativo não batem com as que já foram aplicadas. Peça o ajuste ao Builder, na conversa.',
  'APPLICATION_PAYLOAD_PIN_REFUSED': 'Os arquivos do aplicativo não passaram na verificação de integridade. Peça o ajuste ao Builder, na conversa.',
  'APPLICATION_PAYLOAD_REFUSED': 'Os arquivos do aplicativo não passaram na verificação de integridade. Peça o ajuste ao Builder, na conversa.',
  'APPLICATION_RUNNER_UNAVAILABLE': 'O Conexus não conseguiu alcançar o servidor de aplicativos. A falha foi registrada.',
  'APPLICATION_SERVER_REFUSED': 'O Conexus não conseguiu alcançar o servidor de aplicativos. A falha foi registrada.',
  'APPLICATION_SMOKE_FAILED': 'O aplicativo compilou, mas não abriu na checagem do Conexus. Peça o ajuste ao Builder, na conversa.',
  'APPLICATION_TOTAL_SIZE_REFUSED': 'O aplicativo passou do tamanho que o Conexus aceita. Peça o ajuste ao Builder, na conversa.',
  'BOOT_BROWSER_UNAVAILABLE': 'O Conexus não conseguiu preparar o ambiente de código. A falha foi registrada.',
  'BUILDER_AGENT_COMPLETION_UNAVAILABLE': 'O Builder terminou sem entregar uma resposta. A falha foi registrada.',
  'BUILDER_AGENT_PLATFORM_FAILED': 'Uma falha do Conexus, e não do modelo, interrompeu a execução. As alterações desta execução não foram aplicadas. A falha foi registrada.',
  'BUILDER_AGENT_STALLED': 'O agente parou de responder por uma falha do Conexus, e não do modelo, então a execução foi encerrada. As alterações desta execução não foram aplicadas. A falha foi registrada.',
  'BUILDER_AGENT_TRIPWIRE': 'Um controle interno do Builder encerrou a execução. As alterações desta execução não foram aplicadas. A falha foi registrada.',
  'BUILDER_APPLICATION_SOURCE_REFUSED': 'Os arquivos do aplicativo não passaram na verificação de integridade. Peça o ajuste ao Builder, na conversa.',
  'BUILDER_APP_NOT_FIXED': 'O agente tentou corrigir o app e a verificação do Conexus ainda falha. O que quebrou está na conversa, acima. A versão em uso não mudou, e os arquivos ficaram nesta conversa para o próximo pedido.',
  'BUILDER_CANDIDATE_UNPACK_FAILED': 'O Conexus não conseguiu preparar o ambiente de código. A falha foi registrada.',
  'BUILDER_CHECK_FAILED': 'O código novo quebrou as regras do próprio Projeto, então foi recusado. O Projeto continua no código anterior.',
  'BUILDER_CHECK_IDENTITY_MISMATCH': 'O Conexus não conseguiu preparar o ambiente de código. A falha foi registrada.',
  'BUILDER_CHECK_INSTALL_REFUSED': 'O Conexus não conseguiu preparar o ambiente de código. A falha foi registrada.',
  'BUILDER_CONVERSATIONS_UNAVAILABLE': 'O Conexus falhou ao executar o Builder. A falha foi registrada.',
  'BUILDER_GATEWAY_MODEL_REFUSED': 'O provedor não aceita esse modelo. Escolha outro modelo.',
  'BUILDER_LATE_RESULT_REFUSED': 'Execução interrompida por você.',
  'BUILDER_MESSAGE_ID_UNAVAILABLE': 'O Builder terminou sem entregar uma resposta. A falha foi registrada.',
  'BUILDER_MODEL_AUTH_FAILED': 'Nenhuma conta sua ou compartilhada atende este modelo, ou o provedor a recusou. Conecte uma conta de modelo em Configurações.',
  'BUILDER_MODEL_CONTENT_FILTERED': 'O provedor do modelo bloqueou a resposta. Escolha outro modelo.',
  'BUILDER_MODEL_CONTEXT_LENGTH': 'A conversa ficou maior do que o modelo aceita. Escolha outro modelo.',
  'BUILDER_MODEL_INCOMPLETE': 'O provedor do modelo recusou ou interrompeu o pedido. Escolha outro modelo.',
  'BUILDER_MODEL_NOT_SELECTED': 'Nenhuma conta sua ou compartilhada atende este modelo, ou o provedor a recusou. Conecte uma conta de modelo em Configurações.',
  'BUILDER_MODEL_RATE_LIMITED': 'O provedor do modelo está limitando os pedidos. Tente novamente mais tarde.',
  'BUILDER_MODEL_STEP_TIMEOUT': 'O modelo passou tempo demais gerando uma única resposta, então o Conexus encerrou a execução. As alterações desta execução não foram aplicadas. Tente novamente mais tarde.',
  'BUILDER_MODEL_STREAM_FAILED': 'O provedor do modelo recusou ou interrompeu o pedido. Escolha outro modelo.',
  'BUILDER_PREVIEW_NOT_BUILT': 'O código novo foi aceito, mas o Conexus reiniciou antes de gerar a Prévia. A última Prévia boa continua disponível. O reinício foi registrado.',
  'BUILDER_RESULT_BUNDLE_TOO_LARGE': 'O código novo proposto foi recusado. O Projeto continua no código anterior.',
  'BUILDER_RESULT_CONTENT_TOO_LARGE': 'O código novo proposto foi recusado. O Projeto continua no código anterior.',
  'BUILDER_RESULT_MATERIALIZATION_REFUSED': 'O código novo proposto foi recusado. O Projeto continua no código anterior.',
  'BUILDER_RUNTIME_INPUT_REFUSED': 'O Conexus não conseguiu registrar o andamento da execução. A falha foi registrada.',
  'BUILDER_RUNTIME_RESULT_SCOPE_REFUSED': 'O código novo proposto foi recusado. O Projeto continua no código anterior.',
  'BUILDER_RUN_CANCELLED': 'Execução interrompida por você.',
  'BUILDER_CONVERSATION_SESSION_REFUSED': 'O Conexus não conseguiu registrar o estado da conversa. A falha foi registrada.',
  'BUILDER_RUN_CREATE_FAILED': 'O Conexus não conseguiu registrar o andamento da execução. A falha foi registrada.',
  'BUILDER_RUN_INPUT_REFUSED': 'O Conexus não conseguiu registrar o andamento da execução. A falha foi registrada.',
  'BUILDER_RUN_NOT_ADMITTED': 'O Conexus não conseguiu registrar o andamento da execução. A falha foi registrada.',
  'BUILDER_RUN_TRANSITION_REFUSED': 'O Conexus não conseguiu registrar o andamento da execução. A falha foi registrada.',
  'BUILDER_RUN_PHASE_UPDATE_REFUSED': 'O Conexus não conseguiu registrar o andamento da execução. A falha foi registrada.',
  'BUILDER_SANDBOX_AGENT_USER_REQUIRED': 'O Conexus não conseguiu preparar o ambiente de código. A falha foi registrada.',
  'BUILDER_SANDBOX_COMMAND_INTERFACE_REQUIRED': 'O Conexus não conseguiu preparar o ambiente de código. A falha foi registrada.',
  'BUILDER_SANDBOX_EGRESS_COLLECT_TIMEOUT': 'O Conexus não conseguiu preparar o ambiente de código. A falha foi registrada.',
  'BUILDER_SANDBOX_EGRESS_POLL_FAILED': 'O Conexus não conseguiu preparar o ambiente de código. A falha foi registrada.',
  'BUILDER_SANDBOX_EGRESS_START_FAILED': 'O Conexus não conseguiu preparar o ambiente de código. A falha foi registrada.',
  'BUILDER_SANDBOX_FILE_REFUSED': 'O Conexus não conseguiu preparar o ambiente de código. A falha foi registrada.',
  'BUILDER_SANDBOX_ID_UNAVAILABLE': 'O Conexus não conseguiu preparar o ambiente de código. A falha foi registrada.',
  'BUILDER_SANDBOX_INCARNATION_CHANGED': 'O Conexus não conseguiu preparar o ambiente de código. A falha foi registrada.',
  'BUILDER_SANDBOX_KEEPALIVE_FAILED': 'O Conexus não conseguiu preparar o ambiente de código. A falha foi registrada.',
  'BUILDER_SESSION_DELETE_FAILED': 'O Conexus não conseguiu preparar o ambiente de código. A falha foi registrada.',
  'BUILDER_SOURCE_BASE_MOVED': 'O código do Projeto mudou enquanto esta execução trabalhava, então o resultado não foi aplicado e nada foi sobrescrito.',
  'BUILDER_SOURCE_BASE_PIN_REFUSED': 'O Conexus não conseguiu preparar o ambiente de código. A falha foi registrada.',
  'BUILDER_SOURCE_READ_REFUSED': 'O Conexus não conseguiu ler o código do Projeto. A falha foi registrada.',
  'BUILDER_SOURCE_READ_TREE_TOO_LARGE': 'O Conexus não conseguiu ler o código do Projeto. A falha foi registrada.',
  'BUILDER_SOURCE_READ_UNSAFE_ENTRY': 'O Conexus não conseguiu ler o código do Projeto. A falha foi registrada.',
  'BUILDER_STARTER_ENTRY_INSPECTION_FAILED': 'O Conexus não conseguiu preparar o ambiente de código. A falha foi registrada.',
  'BUILDER_STARTER_ENTRY_UNSAFE': 'O Conexus não conseguiu preparar o ambiente de código. A falha foi registrada.',
  'BUILDER_STARTER_ROOT_REFUSED': 'O Conexus não conseguiu preparar o ambiente de código. A falha foi registrada.',
  'CONEXUS_APP_ROOT_MISSING': 'O Conexus não conseguiu preparar o ambiente de código. A falha foi registrada.',
  'CONEXUS_GIT_FAILED': 'O Conexus não conseguiu preparar o ambiente de código. A falha foi registrada.',
  'CONEXUS_GIT_MAIN_MISSING': 'O Conexus não conseguiu preparar o ambiente de código. A falha foi registrada.',
  'CONEXUS_GIT_MERGE_REFUSED': 'O Conexus não conseguiu preparar o ambiente de código. A falha foi registrada.',
  'CONEXUS_GIT_PROJECT_REFUSED': 'O Conexus não conseguiu preparar o ambiente de código. A falha foi registrada.',
  'CONEXUS_GIT_REF_MOVED': 'O Conexus não conseguiu preparar o ambiente de código. A falha foi registrada.',
  'CONEXUS_GIT_REF_REFUSED': 'O Conexus não conseguiu preparar o ambiente de código. A falha foi registrada.',
  'CONEXUS_GIT_STARTER_REFUSED': 'O Conexus não conseguiu preparar o ambiente de código. A falha foi registrada.',
  'GOOGLE_AI_PRO_ACCOUNT_UNAVAILABLE': 'O Conexus não conseguiu usar a conta Google AI Pro. A falha foi registrada.',
  'GOOGLE_AI_PRO_BINARY_REFUSED': 'O Conexus não conseguiu usar a conta Google AI Pro. A falha foi registrada.',
  'GOOGLE_AI_PRO_POOL_CLOSED': 'O Conexus não conseguiu usar a conta Google AI Pro. A falha foi registrada.',
  'GOOGLE_AI_PRO_PORT_UNAVAILABLE': 'O Conexus não conseguiu usar a conta Google AI Pro. A falha foi registrada.',
  'GOOGLE_AI_PRO_PROXY_START_FAILED': 'O Conexus não conseguiu usar a conta Google AI Pro. A falha foi registrada.',
  'GOOGLE_AI_PRO_RECORD_REFUSED': 'O Conexus não conseguiu ler a credencial salva desta conta de modelo. Conecte uma conta de modelo em Configurações.',
  'GOOGLE_AI_PRO_ROUTER_UNAVAILABLE': 'O Conexus não conseguiu usar a conta Google AI Pro. A falha foi registrada.',
  'GOOGLE_AI_PRO_STORED_RECORD_REFUSED': 'O Conexus não conseguiu ler a credencial salva desta conta de modelo. Conecte uma conta de modelo em Configurações.',
  'HUB_RESTART': 'O Conexus reiniciou durante a execução. O reinício foi registrado.',
  'MANIFEST_REFUSED': 'O servidor do aplicativo tem uma definição que o Conexus não aceita. Peça o ajuste ao Builder, na conversa.',
  'MODEL_ACCOUNT_PROBE_NOT_CALLABLE': 'O Conexus falhou ao executar o Builder. A falha foi registrada.',
  'OPENAI_CODEX_MODEL_REFUSED': 'O provedor não aceita esse modelo. Escolha outro modelo.',
  'OPENAI_CODEX_STORED_RECORD_REFUSED': 'O Conexus não conseguiu ler a credencial salva desta conta de modelo. Conecte uma conta de modelo em Configurações.',
  'SERVER_TREE_REFUSED': 'O servidor do aplicativo tem arquivos que o Conexus não aceita. Peça o ajuste ao Builder, na conversa.',
  'USER_CANCELLED': 'Execução interrompida por você.',
  'BUILDER_QUESTION_EXPIRED': 'A pergunta ficou sem resposta e foi encerrada. A sua próxima mensagem continua o trabalho.',
  'BUILDER_QUESTION_NOT_RELEASED': 'O Builder não conseguiu encerrar a pergunta. A falha foi registrada.',
  'BUILDER_SOURCE_ADMISSION_FAILED': 'A mudança não entrou no app. A falha foi registrada.',
  'BUILDER_RUN_SETTLE_LOST': 'O Conexus perdeu o fim deste trabalho. A falha foi registrada.',
  'APPLICATION_COMPILER_OUTPUT_SYMLINK_REFUSED': 'Os arquivos do aplicativo têm um formato que o Conexus não aceita. Peça o ajuste ao Builder, na conversa.',
  'APPLICATION_COMPILER_OUTPUT_NON_REGULAR_REFUSED': 'Os arquivos do aplicativo têm um formato que o Conexus não aceita. Peça o ajuste ao Builder, na conversa.',
  'APPLICATION_RUNNER_RELEASE_REFUSED': 'O Conexus não conseguiu alcançar o servidor de aplicativos. A falha foi registrada.',
  'INPUT_REFUSED': 'Algum campo tem um valor que o app não aceita.',
  'INPUT_TOO_LARGE': 'Os dados enviados são grandes demais.',
  'OPERATION_NOT_FOUND': 'Essa operação não existe neste app.',
  'HANDLER_TIMEOUT': 'A operação demorou mais que o permitido. Tente novamente mais tarde.',
  'RESPONSE_TOO_LARGE': 'Há resultados demais para mostrar. Use um filtro para reduzir a lista.',
  'DATABASE_UNAVAILABLE': 'Os dados salvos do app estão indisponíveis. A falha foi registrada.',
  'APPLICATION_RUNNER_BUSY': 'O app está ocupado com outros pedidos agora. Tente novamente mais tarde.',
  'APPLICATION_PROJECT_BUSY': 'Este app já tem pedidos demais em andamento. Tente novamente mais tarde.',
  'SERVER_TREE_TOO_LARGE': 'O aplicativo passou do tamanho que o Conexus aceita. Peça o ajuste ao Builder, na conversa.',
  'HANDLER_FAILED': 'Esta operação do app falhou.',
  'HANDLER_LOAD_FAILED': 'Esta operação do app falhou.',
  'HANDLER_EXPORT_MISSING': 'Esta operação do app falhou.',
  'HANDLER_OUTPUT_UNSERIALIZABLE': 'Esta operação do app falhou.',
  'HANDLER_OUTPUT_REFUSED': 'Esta operação do app falhou.',
  'HANDLER_CRASHED': 'Esta operação do app falhou.',
  'WORKER_FAILED': 'O Conexus falhou ao executar o app. A falha foi registrada.',
  'WORKER_JOB_REFUSED': 'O Conexus falhou ao executar o app. A falha foi registrada.',
  'CONNECTOR_SOCKET_REFUSED': 'O Conexus falhou ao executar o app. A falha foi registrada.',
  'CONTENT_TYPE_REFUSED': 'O Conexus não aceitou o formato deste pedido.',
  'APPLICATION_NOT_FOUND': 'Não encontramos este app.',
  'MEMORY_OBSERVATION_FAILED': 'Não foi possível guardar as mensagens na memória. O Builder refaz isso na próxima mensagem.',
  'MEMORY_REFLECTION_FAILED': 'Não foi possível resumir as observações. O Builder refaz isso na próxima mensagem.',
  'MODEL_LOGIN_OPENAI_REFUSED': 'A OpenAI recusou a entrada.',
  'MODEL_LOGIN_ANTHROPIC_REFUSED': 'A Anthropic recusou esse código. Pode ser que ele não tenha sido copiado inteiro.',
  'MODEL_LOGIN_GOOGLE_REFUSED': 'O Google recusou a entrada.',
  'APPLICATION_NO_ACCESS': 'Você não tem acesso a este aplicativo. Peça a quem administra o Conexus.',
  'APPLICATION_EMAIL_NOT_VERIFIED': 'Você não tem acesso a este aplicativo porque seu e-mail ainda não foi verificado.',
  'APPLICATION_SIGN_IN_FAILED': 'O serviço de login não concluiu a entrada. Entre de novo.',
  'APPLICATION_NOT_READY': 'Este app ainda não está pronto para receber pedidos.',
  'APPLICATION_SIGN_IN_REQUIRED': 'Você precisa entrar no Conexus para usar este app. Entre na sua conta para continuar.',
  'PREVIEW_REFUSED': 'Esta prévia não aceita o pedido.',
  'NOT_GRANTED': 'Este app perdeu o acesso ao sistema da empresa. Quem administra o Workspace precisa vincular a Conexão outra vez. Peça a quem administra o Conexus.',
  'CONNECTOR_UNCONFIGURED': 'A integração com o sistema da empresa não está configurada. A falha foi registrada.',
  'CREDENTIAL_REFUSED': 'O sistema da empresa recusou o acesso. Avise quem administra a integração. Peça a quem administra o Conexus.',
  'PROVIDER_TIMEOUT': 'O sistema da empresa não respondeu a tempo. Tente novamente mais tarde.',
  'PROVIDER_UNAVAILABLE': 'O sistema da empresa está indisponível agora. Tente novamente mais tarde.',
  'PROVIDER_ERROR': 'O sistema da empresa respondeu com um erro.',
  'RESPONSE_REFUSED': 'O Conexus não aceitou a resposta do sistema da empresa.',
  'CALL_LIMIT': 'Este app fez chamadas demais ao sistema da empresa. Tente novamente mais tarde.',
  'SERVICE_REFUSED': 'Esta operação não é permitida pela conexão com o sistema da empresa.',
  'CONNECTOR_PLATFORM_FAILED': 'O Conexus falhou ao ler o sistema da empresa. A falha foi registrada.',
} as const satisfies Readonly<Record<string, string>>
