export const OIDC_TRANSACTION_SECONDS = 600

export const APPLICATION_SIGN_IN_COOKIE_SECONDS = 720

export const INVITATION_DAYS = 14

export const HUB_IDLE_SECONDS = 1800

export const HUB_ABSOLUTE_SECONDS = 28800

export const APPLICATION_ABSOLUTE_SECONDS = 28800

export const PROVIDER_RECHECK_SECONDS = 300

export const PREVIEW_SECONDS = 900

export const APPLICATION_HANDOFF_SECONDS = 60

export const PREVIEW_HANDOFF_SECONDS = 30
