import { createHash, randomUUID } from 'node:crypto'
import { mkdir, rm, writeFile } from 'node:fs/promises'
import { dirname, join } from 'node:path'
import pg from 'pg'
import { ensurePreviewAllocation, planMigrations, previewAllocation, PROVISIONER_ROLE, readLedger, resetPreviewSchema, roleCredential } from './data-plane.js'
import type { PreviewAllocation } from './data-plane.js'
import { openPgRelay } from './pg-relay.js'
import { runWorker, SANDBOX_DATABASE_HOST } from './sandbox.js'
import type { SandboxConfig, WorkerOutcome } from './sandbox.js'
import { admitManifest, SERVER_MANIFEST_PATH, SERVER_ROOT, schemaViolation } from './server-manifest.js'
import type { ServerManifest } from './server-manifest.js'
import type { WorkerJob } from './worker.js'

/** One file of the admitted artifact's `conexus-server/` tree, as the Hub read it from the registry. */
export type ServerFile = Readonly<{ path: string; sha256: string; content: string }>

export type RunnerLimits = Readonly<{
  invokeTimeoutMs: number
  migrateTimeoutMs: number
  inputBytes: number
  responseBytes: number
  concurrency: number
  sessionsPerInvocation: number
}>

export const DEFAULT_LIMITS: RunnerLimits = Object.freeze({
  invokeTimeoutMs: 5000,
  migrateTimeoutMs: 30_000,
  inputBytes: 64 * 1024,
  responseBytes: 1024 * 1024,
  concurrency: 4,
  sessionsPerInvocation: 2,
})

export type SupervisorConfig = Readonly<{
  stateDir: string
  runtimeDir: string
  cluster: Readonly<{ host: string; port: number }>
  database: string
  provisionerPassword: string
  credentialKey: Uint8Array
  limits?: RunnerLimits
  sandbox?: SandboxConfig
}>

export type Reply = Readonly<{ status: number; body: unknown }>

export type PrepareResult =
  | Readonly<{ state: 'READY'; reset: boolean; applied: readonly string[] }>
  | Readonly<{ state: 'MIGRATION_FAILED'; detail: string }>

const refusal = (status: number, code: string, detail?: string): Reply =>
  Object.freeze({ status, body: { error: detail === undefined ? { code } : { code, detail } } })

const MAX_FILES = 128
const MAX_FILE_BYTES = 4 * 1024 * 1024
const SERVER_PATH = new RegExp(`^${SERVER_ROOT}/(?:[a-z0-9][A-Za-z0-9_.-]{0,127}/){0,6}[A-Za-z0-9][A-Za-z0-9_.-]{0,127}$`)

/** The admitted server tree: its manifest and the handler files that land at /app in the sandbox. */
type ServerTree = Readonly<{ manifest: ServerManifest; modules: ReadonlyMap<string, Buffer> }>

// The Hub sends the files it retained for this artifact; the runner still checks every one, because
// this is where generated bytes turn into something that runs.
export const admitServerTree = (files: readonly ServerFile[]): ServerTree => {
  if (!Array.isArray(files) || files.length === 0 || files.length > MAX_FILES) throw new Error('SERVER_TREE_REFUSED')
  const modules = new Map<string, Buffer>()
  let manifest: ServerManifest | null = null
  for (const file of files) {
    if (typeof file?.path !== 'string' || !SERVER_PATH.test(file.path) || file.path.split('/').some((part: string) => part === '..' || part === '.') ||
      typeof file.content !== 'string' || typeof file.sha256 !== 'string') throw new Error('SERVER_TREE_REFUSED')
    const bytes = Buffer.from(file.content, 'base64')
    if (bytes.byteLength > MAX_FILE_BYTES || createHash('sha256').update(bytes).digest('hex') !== file.sha256) throw new Error('SERVER_TREE_REFUSED')
    const relative = file.path.slice(SERVER_ROOT.length + 1)
    if (file.path === SERVER_MANIFEST_PATH) manifest = admitManifest(JSON.parse(bytes.toString('utf8')), 'server') as ServerManifest
    else if (relative.endsWith('.mjs') && !modules.has(relative)) modules.set(relative, bytes)
    else throw new Error('SERVER_TREE_REFUSED')
  }
  if (!manifest) throw new Error('SERVER_TREE_REFUSED')
  for (const operation of Object.values(manifest.operations)) if (!modules.has(operation.module)) throw new Error('SERVER_TREE_REFUSED')
  return Object.freeze({ manifest, modules })
}

const STATUS_BY_CODE: Readonly<Record<string, number>> = Object.freeze({
  HANDLER_FAILED: 500,
  HANDLER_LOAD_FAILED: 500,
  HANDLER_EXPORT_MISSING: 500,
  HANDLER_OUTPUT_UNSERIALIZABLE: 500,
  WORKER_FAILED: 500,
  WORKER_JOB_REFUSED: 500,
  RESPONSE_TOO_LARGE: 502,
  DATABASE_UNAVAILABLE: 503,
})

export const createSupervisor = (config: SupervisorConfig) => {
  const limits = config.limits ?? DEFAULT_LIMITS
  const provisioner = new pg.Pool({
    ...config.cluster, database: config.database, user: PROVISIONER_ROLE, password: config.provisionerPassword,
    max: 2, application_name: 'conexus-app-runner', connectionTimeoutMillis: 5000,
  })
  provisioner.on('error', () => undefined)
  const credential = (role: string): string => roleCredential(config.credentialKey, role)
  const preparing = new Map<string, Promise<unknown>>()
  // Every Project's migrations run through one chain, so a build storm cannot start many expensive
  // migrations against the shared cluster at once. Invocations have their own bound below.
  let migrationChain: Promise<unknown> = Promise.resolve()
  let running = 0

  // One sandboxed worker with its own directory and its own pinned database socket, removed after.
  const inSandbox = async (input: Readonly<{
    role: string
    modules?: ReadonlyMap<string, Buffer>
    job: (login: WorkerJob['login']) => WorkerJob
    timeoutMs: number
  }>): Promise<Readonly<{ outcome: WorkerOutcome; refusedSessions: readonly string[] }>> => {
    // A unix socket path is capped at 107 bytes, so the per-invocation directory is kept short.
    const directory = join(config.stateDir, 'i', randomUUID())
    const appDir = join(directory, 'app')
    const socket = join(directory, 'pg.sock')
    await mkdir(directory, { recursive: true, mode: 0o700 })
    try {
      if (input.modules) {
        for (const [path, bytes] of input.modules) {
          await mkdir(dirname(join(appDir, path)), { recursive: true, mode: 0o700 })
          await writeFile(join(appDir, path), bytes, { mode: 0o400 })
        }
      }
      const relay = await openPgRelay({
        socketPath: socket, upstream: config.cluster, pin: { user: input.role, database: config.database },
        password: credential(input.role), maxSessions: limits.sessionsPerInvocation,
      })
      try {
        const outcome = await runWorker({
          ...(config.sandbox ? { config: config.sandbox } : {}),
          runtimeDir: config.runtimeDir,
          ...(input.modules ? { appDir } : {}),
          databaseSocket: socket,
          job: input.job({ host: SANDBOX_DATABASE_HOST, user: input.role, database: config.database }),
          timeoutMs: input.timeoutMs,
          resultLimit: limits.responseBytes,
        })
        return { outcome, refusedSessions: relay.refused() }
      } finally {
        await relay.close()
      }
    } finally {
      await rm(directory, { recursive: true, force: true })
    }
  }

  const withProvisioner = async <T>(work: (client: pg.PoolClient) => Promise<T>): Promise<T> => {
    const client = await provisioner.connect()
    try { return await work(client) } finally { client.release() }
  }

  const migrate = async (allocation: PreviewAllocation, manifest: ServerManifest): Promise<PrepareResult> => {
    const plan = await withProvisioner(async (client) => {
      const allocate = () => ensurePreviewAllocation(client, { allocation, database: config.database, credential })
      await allocate()
      const first = planMigrations(await readLedger(client, allocation), manifest.migrations)
      if (!first.reset) return first
      await resetPreviewSchema(client, allocation)
      await allocate()
      return planMigrations([], manifest.migrations)
    })
    if (plan.pending.length === 0) return { state: 'READY', reset: plan.reset, applied: [] }
    const { outcome } = await inSandbox({
      role: allocation.migrationRole,
      job: (login) => ({ kind: 'migrate', login, schema: allocation.schema, plan: plan.pending }),
      timeoutMs: limits.migrateTimeoutMs,
    })
    if (outcome.kind === 'RESULT' && outcome.result.ok) return { state: 'READY', reset: plan.reset, applied: plan.pending.map((migration) => migration.name) }
    // A migration runs no generated JavaScript, so the worker's own log is safe to hand back.
    const detail = outcome.kind === 'RESULT' && !outcome.result.ok ? outcome.result.detail ?? outcome.result.code : `${outcome.kind}${outcome.kind === 'CRASHED' ? ` ${outcome.signal ?? outcome.exitCode}` : ''} ${outcome.logs.slice(-300)}`.trim()
    return { state: 'MIGRATION_FAILED', detail }
  }

  /**
   * Converges the Project's Preview schema on the artifact's migrations before its Preview is offered.
   * One Project migrates at a time.
   */
  const prepare = async (input: Readonly<{ projectId: string; files: readonly ServerFile[] }>): Promise<PrepareResult> => {
    const allocation = previewAllocation(input.projectId)
    const tree = admitServerTree(input.files)
    const previous = preparing.get(allocation.projectId) ?? Promise.resolve()
    const current = previous.catch(() => undefined).then(() => {
      const migrated = migrationChain.catch(() => undefined).then(() => migrate(allocation, tree.manifest))
      migrationChain = migrated.catch(() => undefined)
      return migrated
    })
    preparing.set(allocation.projectId, current)
    try {
      return await current
    } finally {
      if (preparing.get(allocation.projectId) === current) preparing.delete(allocation.projectId)
    }
  }

  const invoke = async (input: Readonly<{ projectId: string; operation: string; input: unknown; files: readonly ServerFile[] }>): Promise<Reply> => {
    const allocation = previewAllocation(input.projectId)
    let tree: ServerTree
    try {
      tree = admitServerTree(input.files)
    } catch {
      return refusal(500, 'SERVER_TREE_REFUSED')
    }
    const operation = Object.hasOwn(tree.manifest.operations, input.operation) ? tree.manifest.operations[input.operation] : undefined
    if (!operation) return refusal(404, 'OPERATION_NOT_FOUND')
    if (Buffer.byteLength(JSON.stringify(input.input ?? null)) > limits.inputBytes) return refusal(413, 'INPUT_TOO_LARGE')
    const inputViolation = schemaViolation(operation.input, input.input)
    if (inputViolation) return refusal(400, 'INPUT_REFUSED', inputViolation)
    if (running >= limits.concurrency) return refusal(429, 'RUNNER_BUSY')
    running += 1
    try {
      const { outcome } = await inSandbox({
        role: allocation.runtimeRole,
        modules: tree.modules,
        job: (login) => ({ kind: 'invoke', login, module: `/app/${operation.module}`, export: operation.export, input: input.input, responseLimit: limits.responseBytes }),
        timeoutMs: limits.invokeTimeoutMs,
      })
      if (outcome.kind === 'CRASHED') return refusal(500, 'HANDLER_CRASHED', outcome.signal ?? `exit ${outcome.exitCode}`)
      if (outcome.kind !== 'RESULT') return outcome.kind === 'TIMEOUT' ? refusal(504, 'HANDLER_TIMEOUT') : refusal(502, 'RESPONSE_TOO_LARGE')
      if (!outcome.result.ok) return refusal(STATUS_BY_CODE[outcome.result.code] ?? 500, outcome.result.code, outcome.result.detail)
      const outputViolation = schemaViolation(operation.output, outcome.result.value)
      if (outputViolation) return refusal(502, 'HANDLER_OUTPUT_REFUSED', outputViolation)
      return { status: 200, body: outcome.result.value }
    } finally {
      running -= 1
    }
  }

  return Object.freeze({
    // The runner's own census: it has one credential, and without it no Project can be served.
    checkProvisioner: () => withProvisioner(async (client) => {
      const { rows } = await client.query('SELECT current_user AS role, current_database() AS database')
      if (rows[0]?.role !== PROVISIONER_ROLE || rows[0]?.database !== config.database) throw new Error('RUNNER_PROVISIONER_REFUSED')
    }),
    prepare,
    invoke,
    close: async () => { await provisioner.end().catch(() => undefined) },
  })
}

export type Supervisor = ReturnType<typeof createSupervisor>
