import { createHash, randomUUID } from 'node:crypto'
import { lstat, mkdir, rm, writeFile } from 'node:fs/promises'
import { basename, dirname, join, resolve } from 'node:path'
import pg from 'pg'
import { convergePreviewAllocations, ensurePreviewAllocation, planMigrations, previewAllocation, PROJECT_ROLE_NAME, PROVISIONER_ROLE, readLedger, releasePreviewAllocation, resetPreviewSchema, restoreRuntimePrivileges } from './data-plane.js'
import type { LedgerRow, MigrationSource, PreviewAllocation } from './data-plane.js'
import { openPgRelay } from './pg-relay.js'
import { RESET_STATEMENT_TIMEOUT_MS } from './requests.js'
import type { RelayTls } from './pg-relay.js'
import { runWorker, SANDBOX_DATABASE_HOST } from './sandbox.js'
import type { SandboxConfig, WorkerOutcome } from './sandbox.js'
import { admitServerTree as admitTree, schemaViolation } from './server-manifest.js'
import type { PrepareResult, ServerFile, ServerManifest, ServerTree } from './server-manifest.js'
import type { WorkerJob } from './wire.js'
import type { Caller } from '../platform/caller.js'
import { Failure } from '../platform/failure.js'
import type { FailureCode } from '../platform/failures.generated.js'
import { failureProblem } from '../http/problem.js'

export type { ServerFile }

type RunnerLimits = Readonly<{
  invokeTimeoutMs: number
  migrateTimeoutMs: number
  inputBytes: number
  responseBytes: number
  concurrency: number
  sessionsPerInvocation: number
}>

const DEFAULT_LIMITS: RunnerLimits = Object.freeze({
  invokeTimeoutMs: 5000,
  migrateTimeoutMs: 30_000,
  inputBytes: 64 * 1024,
  responseBytes: 1024 * 1024,
  concurrency: 4,
  sessionsPerInvocation: 2,
})

export type SupervisorConfig = Readonly<{
  stateDir: string
  runtimeDir: string
  cluster: Readonly<{ host: string; port: number }>
  database: string
  provisionerPassword: string
  relayTls: RelayTls
  limits?: RunnerLimits
  sandbox?: SandboxConfig
  /** The runner's own copy of CONEXUS_CONNECTOR_SOCKET_DIR; absent, no connector socket is admitted. */
  connectorSocketDir?: string
}>

export type Reply = Readonly<{ status: number; body: unknown }>

export type InvokeInput = Readonly<{ projectId: string; operation: string; input: unknown; files: readonly ServerFile[]; caller: Caller; connectorSocket?: string | undefined }>


/**
 * What the runner may do when the applied history is not a prefix of the artifact's migrations:
 * refuse, or reset the Preview schema if the reset starts before resetBefore (epoch ms).
 */
export type OnDivergence = 'REFUSE' | Readonly<{ resetBefore: number }>

// What the worker may report; anything else it names is a handler fault.
const WORKER_CODES = ['HANDLER_FAILED', 'HANDLER_LOAD_FAILED', 'HANDLER_EXPORT_MISSING', 'HANDLER_OUTPUT_UNSERIALIZABLE', 'WORKER_FAILED', 'WORKER_JOB_REFUSED', 'RESPONSE_TOO_LARGE', 'DATABASE_UNAVAILABLE', 'APPLICATION_MIGRATION_FAILED'] as const satisfies readonly FailureCode[]
const workerCodeOf = (code: string): FailureCode => WORKER_CODES.find((known) => known === code) ?? 'HANDLER_FAILED'

/** The runner's reply to an invoke: the row's problem body and status, with the platform's own detail when there is one. */
const refusal = (code: FailureCode, detail?: string): Reply => {
  const problem = failureProblem(new Failure(code))
  return Object.freeze({ status: problem.status, body: detail === undefined ? problem : { ...problem, detail } })
}

// The Hub sends the files it retained for this artifact; the runner still checks every one, because
// this is where generated bytes turn into something that runs.
const admitServerTree = (files: readonly ServerFile[]): ServerTree =>
  admitTree(files, (bytes) => createHash('sha256').update(bytes).digest('hex'))

// The first applied migration the artifact no longer carries unchanged at the same position.
const divergedMigration = (ledger: readonly LedgerRow[], migrations: readonly MigrationSource[]): string =>
  ledger.find((entry, index) => entry.position !== index + 1 || entry.name !== migrations[index]?.name || entry.sha256 !== migrations[index]?.sha256)?.name ?? ''

const divergenceDetail = (name: string): string =>
  `A migração já aplicada ${name} foi alterada, removida ou reordenada. Este Project tem uma aplicação, então os dados dela não foram apagados. Restaure essa migração ao conteúdo aplicado e coloque a mudança em uma nova migração.`

// biome-ignore lint/complexity/noExcessiveLinesPerFunction: debt: owning wave
export const createSupervisor = (config: SupervisorConfig) => {
  const limits = config.limits ?? DEFAULT_LIMITS
  const provisioner = new pg.Pool({
    ...config.cluster, database: config.database, user: PROVISIONER_ROLE, password: config.provisionerPassword,
    max: 2, application_name: 'conexus-app-runner', connectionTimeoutMillis: 5000,
  })
  provisioner.on('error', () => undefined)
  const preparing = new Map<string, Promise<unknown>>()
  // Every Project's migrations run through one chain, so a build storm cannot start many expensive
  // migrations against the shared cluster at once. Invocations have their own bound below.
  let migrationChain: Promise<unknown> = Promise.resolve()
  let running = 0

  // Only a socket directly inside the runner's configured directory, never a symlink or a file.
  const admitConnectorSocket = async (path: string): Promise<boolean> => {
    const directory = config.connectorSocketDir
    if (!directory || resolve(path) !== path || dirname(path) !== resolve(directory) || basename(path).startsWith('.')) return false
    const stat = await lstat(path).catch(() => null)
    return stat?.isSocket() === true
  }

  // One sandboxed worker with its own directory and its own pinned database socket, removed after.
  const inSandbox = async (input: Readonly<{
    role: string
    modules?: ReadonlyMap<string, Buffer>
    connectorSocket?: string
    job: (login: WorkerJob['login']) => WorkerJob
    timeoutMs: number
  }>): Promise<Readonly<{ outcome: WorkerOutcome; refusedSessions: readonly string[] }>> => {
    // A unix socket path is capped at 107 bytes, so the per-invocation directory is kept short.
    const directory = join(config.stateDir, 'i', randomUUID())
    const appDir = join(directory, 'app')
    const socket = join(directory, 'pg.sock')
    await mkdir(directory, { recursive: true, mode: 0o700 })
    try {
      if (input.modules) {
        for (const [path, bytes] of input.modules) {
          await mkdir(dirname(join(appDir, path)), { recursive: true, mode: 0o700 })
          await writeFile(join(appDir, path), bytes, { mode: 0o400 })
        }
      }
      const relay = await openPgRelay({
        socketPath: socket, upstream: config.cluster, pin: { user: input.role, database: config.database },
        tls: config.relayTls, maxSessions: limits.sessionsPerInvocation,
      })
      try {
        const outcome = await runWorker({
          ...(config.sandbox ? { config: config.sandbox } : {}),
          runtimeDir: config.runtimeDir,
          ...(input.modules ? { appDir } : {}),
          databaseSocket: socket,
          ...(input.connectorSocket ? { connectorSocket: input.connectorSocket } : {}),
          job: input.job({ host: SANDBOX_DATABASE_HOST, user: input.role, database: config.database }),
          timeoutMs: input.timeoutMs,
          resultLimit: limits.responseBytes,
        })
        return { outcome, refusedSessions: relay.refused() }
      } finally {
        await relay.close()
      }
    } finally {
      await rm(directory, { recursive: true, force: true })
    }
  }

  const withProvisioner = async <T>(work: (client: pg.PoolClient) => Promise<T>): Promise<T> => {
    const client = await provisioner.connect()
    try { return await work(client) } finally { client.release() }
  }

  const migrate = async (allocation: PreviewAllocation, manifest: ServerManifest, onDivergence: OnDivergence): Promise<PrepareResult> => {
    const plan = await withProvisioner(async (client) => {
      const allocate = () => ensurePreviewAllocation(client, { allocation, database: config.database })
      await allocate()
      const ledger = await readLedger(client, allocation)
      const first = planMigrations(ledger, manifest.migrations)
      if (!first.reset) return first
      if (onDivergence === 'REFUSE') return { diverged: divergedMigration(ledger, manifest.migrations) }
      await client.query('BEGIN')
      try {
        await client.query(`SET LOCAL statement_timeout = ${RESET_STATEMENT_TIMEOUT_MS}`)
        if (Date.now() >= onDivergence.resetBefore) throw new Failure('INTERNAL_UNEXPECTED', { details: { invariant: 'PREVIEW_RESET_EXPIRED' } })
        await resetPreviewSchema(client, allocation)
        await client.query('COMMIT')
      } catch (error) {
        await client.query('ROLLBACK').catch(() => undefined)
        throw error
      }
      await allocate()
      return { ...planMigrations([], manifest.migrations), reset: true }
    })
    if ('diverged' in plan) return { state: 'MIGRATION_HISTORY_DIVERGED', detail: divergenceDetail(plan.diverged) }
    if (plan.pending.length === 0) return { state: 'READY', reset: plan.reset, applied: [] }
    const { outcome } = await inSandbox({
      role: allocation.migrationRole,
      job: (login) => ({ kind: 'migrate', login, schema: allocation.schema, plan: plan.pending }),
      timeoutMs: limits.migrateTimeoutMs,
    }).finally(() => withProvisioner((client) => restoreRuntimePrivileges(client, allocation)))
    if (outcome.kind === 'RESULT' && outcome.result.ok) return { state: 'READY', reset: plan.reset, applied: plan.pending.map((migration) => migration.name) }
    // A migration runs no generated JavaScript, so the worker's own log is safe to hand back.
    const detail = outcome.kind === 'RESULT' && !outcome.result.ok ? outcome.result.detail ?? outcome.result.code : `${outcome.kind}${outcome.kind === 'CRASHED' ? ` ${outcome.signal ?? outcome.exitCode}` : ''} ${outcome.logs.slice(-300)}`.trim()
    return { state: 'MIGRATION_FAILED', detail }
  }

  /**
   * Converges the Project's Preview schema on the artifact's migrations before its Preview is offered.
   * One Project migrates at a time.
   */
  const prepare = async (input: Readonly<{ projectId: string; files: readonly ServerFile[]; onDivergence: OnDivergence }>): Promise<PrepareResult> => {
    const allocation = previewAllocation(input.projectId)
    const tree = admitServerTree(input.files)
    const previous = preparing.get(allocation.projectId) ?? Promise.resolve()
    const current = previous.catch(() => undefined).then(() => {
      const migrated = migrationChain.catch(() => undefined).then(() => migrate(allocation, tree.manifest, input.onDivergence))
      migrationChain = migrated.catch(() => undefined)
      return migrated
    })
    preparing.set(allocation.projectId, current)
    try {
      return await current
    } finally {
      if (preparing.get(allocation.projectId) === current) preparing.delete(allocation.projectId)
    }
  }

  /**
   * Releases a Project's Preview allocation for good: its schema and its two roles. Called once, when
   * the Project itself is deleted. Waits behind any migration already in flight for the Project so the
   * drop never races a CREATE the migration worker still holds open.
   */
  const release = async (input: Readonly<{ projectId: string }>): Promise<void> => {
    const allocation = previewAllocation(input.projectId)
    const previous = preparing.get(allocation.projectId) ?? Promise.resolve()
    await previous.catch(() => undefined)
    await withProvisioner((client) => releasePreviewAllocation(client, allocation))
  }

  const invoke = async (input: InvokeInput): Promise<Reply> => {
    const allocation = previewAllocation(input.projectId)
    let tree: ServerTree
    try {
      tree = admitServerTree(input.files)
    } catch {
      return refusal('SERVER_TREE_REFUSED')
    }
    const operation = Object.hasOwn(tree.manifest.operations, input.operation) ? tree.manifest.operations[input.operation] : undefined
    if (!operation) return refusal('OPERATION_NOT_FOUND')
    if (Buffer.byteLength(JSON.stringify(input.input ?? null)) > limits.inputBytes) return refusal('INPUT_TOO_LARGE')
    const inputViolation = schemaViolation(operation.input, input.input, true)
    if (inputViolation) return refusal('INPUT_REFUSED', inputViolation)
    if (input.connectorSocket !== undefined && !await admitConnectorSocket(input.connectorSocket)) return refusal('CONNECTOR_SOCKET_REFUSED')
    if (running >= limits.concurrency) return refusal('APPLICATION_RUNNER_BUSY')
    running += 1
    try {
      const { outcome } = await inSandbox({
        role: allocation.runtimeRole,
        modules: tree.modules,
        ...(input.connectorSocket ? { connectorSocket: input.connectorSocket } : {}),
        job: (login) => ({ kind: 'invoke', login, module: `/app/${operation.module}`, export: operation.export, input: input.input, caller: input.caller, responseLimit: limits.responseBytes, connector: input.connectorSocket !== undefined }),
        timeoutMs: limits.invokeTimeoutMs,
      })
      if (outcome.kind === 'CRASHED') return refusal('HANDLER_CRASHED', outcome.signal ?? `exit ${outcome.exitCode}`)
      if (outcome.kind !== 'RESULT') return outcome.kind === 'TIMEOUT' ? refusal('HANDLER_TIMEOUT') : refusal('RESPONSE_TOO_LARGE')
      if (!outcome.result.ok) {
        const code = workerCodeOf(outcome.result.code)
        return refusal(code, code === 'HANDLER_EXPORT_MISSING' ? operation.export : outcome.result.detail)
      }
      const outputViolation = schemaViolation(operation.output, outcome.result.value, false)
      if (outputViolation) return refusal('HANDLER_OUTPUT_REFUSED', outputViolation)
      return { status: 200, body: outcome.result.value }
    } finally {
      running -= 1
    }
  }

  return Object.freeze({
    // The runner's own census: it has one credential, and without it no Project can be served. A
    // routine language PUBLIC or a Project role may use would let a migration leave code behind that
    // later runs with its authority, so the runner does not serve on such a database.
    checkProvisioner: () => withProvisioner(async (client) => {
      const { rows } = await client.query('SELECT current_user AS role, current_database() AS database')
      if (rows[0]?.role !== PROVISIONER_ROLE || rows[0]?.database !== config.database) throw new Failure('INTERNAL_UNEXPECTED', { details: { invariant: 'RUNNER_PROVISIONER_REFUSED' } })
      const { rows: usable } = await client.query(`SELECT l.lanname FROM pg_language l WHERE l.lanpltrusted AND (
        EXISTS (SELECT 1 FROM aclexplode(coalesce(l.lanacl, acldefault('l', l.lanowner))) acl WHERE acl.grantee = 0 AND acl.privilege_type = 'USAGE')
        OR EXISTS (SELECT 1 FROM pg_roles r WHERE r.rolname ~ $1 AND has_language_privilege(r.oid, l.oid, 'USAGE')))
        ORDER BY 1`, [PROJECT_ROLE_NAME.source])
      if (usable.length > 0) throw new Failure('INTERNAL_UNEXPECTED', { details: { invariant: 'RUNNER_ROUTINE_LANGUAGE_USABLE', languages: usable.map((row) => String(row.lanname)).join(',') } })
      return convergePreviewAllocations(client, config.database)
    }),
    prepare,
    invoke,
    release,
    close: async () => { await provisioner.end().catch(() => undefined) },
  })
}
