import { readFileSync, readdirSync } from 'node:fs'
import { isAbsolute, join, relative, resolve } from 'node:path'
import type { CommandResult, SandboxFileInput } from '@mastra/core/workspace'
import { redactEvidence } from './check/problems.js'
import { Failure } from '../platform/failure.js'

export type FixedApplicationStarterResult = 'MATERIALIZED' | 'PRESERVED'

export type FixedApplicationStarterWorkspace = Readonly<{
  directCommand(command: string, args: readonly string[]): Promise<CommandResult>
  writeFiles(files: SandboxFileInput[]): Promise<void>
}>

const STARTER_TEMPLATE_ROOT = 'apps/hub/starter-template/files'

const starterTemplatePaths = (directory: string): string[] =>
  readdirSync(directory, { withFileTypes: true }).flatMap((entry) =>
    entry.isDirectory() ? starterTemplatePaths(join(directory, entry.name)) : [join(directory, entry.name)])

/**
 * The files of a new Project's `app/`, read from `apps/hub/starter-template/files` (found from the
 * Hub process's working directory, like the Project knowledge). That folder holds the starter as
 * real source, so it can be type checked and built as an app; the components under `components/ui`
 * are generated by `scripts/generate-starter-components.mjs`.
 */
export const fixedApplicationStarterFiles = (cwd: string = process.cwd()): readonly Readonly<{ path: string; content: string }>[] => {
  const root = resolve(cwd, STARTER_TEMPLATE_ROOT)
  return Object.freeze(starterTemplatePaths(root)
    .map((file) => relative(root, file))
    .sort((left, right) => (left < right ? -1 : left > right ? 1 : 0))
    .map((path) => Object.freeze({ path, content: readFileSync(join(root, path), 'utf8') })))
}

// A Project's shape file. It names the shape, which pins the compiler contract the app is built for.
// The check that admits its source is the Hub's own script, never a file of the Project's.
export const APPLICATION_SHAPE_FILES = Object.freeze([
  Object.freeze({ path: 'conexus.json', content: `${JSON.stringify({ shape: 'REACT_VITE_V2' }, null, 2)}\n` }),
] as const)

// Kept out of every candidate: the link the build makes into app/, and the files the platform
// generates from the manifest, which it regenerates for every check and so never takes from a run.
export const APPLICATION_CHECK_EXCLUDED = Object.freeze(['app/node_modules', '*.gen.ts'])

const EVIDENCE_LIMIT = 400

// A failed command's output is the only record of why it failed, so it is kept, but it can carry a
// Git header or a token from whatever produced it, and it goes to a log.
export const commandEvidence = (text: string): string => {
  const redacted = redactEvidence(text)
  return redacted.length > EVIDENCE_LIMIT ? `${redacted.slice(0, EVIDENCE_LIMIT)}…` : redacted
}

const inspectEntry = async (
  directCommand: FixedApplicationStarterWorkspace['directCommand'],
  appPath: string,
): Promise<'ABSENT' | 'PRESENT' | 'UNSAFE'> => {
  const result = await directCommand('sh', [
    '-c',
    'if [ -L "$1" ]; then printf UNSAFE; elif [ -e "$1" ]; then printf PRESENT; else printf ABSENT; fi',
    'conexus-fixed-application-starter',
    appPath,
  ])
  const state = result.stdout.trim()
  if (result.exitCode === 0 && (state === 'ABSENT' || state === 'PRESENT' || state === 'UNSAFE')) return state
  throw new Failure('BUILDER_STARTER_ENTRY_INSPECTION_FAILED', {
    cause: { exitCode: result.exitCode, stdout: commandEvidence(result.stdout), stderr: commandEvidence(result.stderr) },
  })
}

export const materializeFixedApplicationStarter = async ({
  repositoryRoot,
  directCommand,
  writeFiles,
}: Readonly<{
  repositoryRoot: string
  directCommand: FixedApplicationStarterWorkspace['directCommand']
  writeFiles: FixedApplicationStarterWorkspace['writeFiles']
}>): Promise<FixedApplicationStarterResult> => {
  if (!isAbsolute(repositoryRoot) || repositoryRoot.includes('\0')) throw new Failure('BUILDER_STARTER_ROOT_REFUSED')
  const appPath = join(repositoryRoot, 'app')
  const entry = await inspectEntry(directCommand, appPath)
  if (entry === 'UNSAFE') throw new Failure('BUILDER_STARTER_ENTRY_UNSAFE')
  if (entry === 'PRESENT') return 'PRESERVED'

  await writeFiles(fixedApplicationStarterFiles().map((file) => ({
    path: join(repositoryRoot, file.path),
    content: file.content,
  })))
  return 'MATERIALIZED'
}

/** Writes each shape file the checkout lacks; an existing one is the repository's. */
export const materializeApplicationShape = async ({
  repositoryRoot,
  directCommand,
  writeFiles,
}: Readonly<{
  repositoryRoot: string
  directCommand: FixedApplicationStarterWorkspace['directCommand']
  writeFiles: FixedApplicationStarterWorkspace['writeFiles']
}>): Promise<void> => {
  if (!isAbsolute(repositoryRoot) || repositoryRoot.includes('\0')) throw new Failure('BUILDER_STARTER_ROOT_REFUSED')
  const missing: SandboxFileInput[] = []
  for (const file of APPLICATION_SHAPE_FILES) {
    const path = join(repositoryRoot, file.path)
    const entry = await inspectEntry(directCommand, path)
    if (entry === 'UNSAFE') throw new Failure('BUILDER_STARTER_ENTRY_UNSAFE')
    if (entry === 'ABSENT') missing.push({ path, content: file.content })
  }
  if (missing.length > 0) await writeFiles(missing)
}
