import type { BuilderRunSummary } from './store.js'

export type BuilderFailureCategory =
  | 'ENVIRONMENT_PREPARATION_FAILED'
  | 'MODEL_CREDENTIAL_REFUSED'
  | 'MODEL_RATE_LIMITED'
  | 'MODEL_REQUEST_REFUSED'
  | 'SOURCE_RESULT_REJECTED'
  | 'APPLICATION_BUILD_FAILED'
  | 'RUN_CANCELLED'
  | 'RUN_INTERRUPTED'
  | 'INTERNAL_ERROR'

export type WireBuilderRun = Omit<BuilderRunSummary, 'failureCode'> & Readonly<{
  failureCategory: BuilderFailureCategory | null
  failureCode: string | null
}>

const CATEGORY_BY_CODE: Readonly<Record<string, BuilderFailureCategory>> = Object.freeze({
  BUILDER_SOURCE_MATERIALIZATION_REFUSED: 'ENVIRONMENT_PREPARATION_FAILED',
  BUILDER_SOURCE_BUNDLE_REFUSED: 'ENVIRONMENT_PREPARATION_FAILED',
  BUILDER_SOURCE_READ_REFUSED: 'ENVIRONMENT_PREPARATION_FAILED',
  BUILDER_SOURCE_FILE_REFUSED: 'ENVIRONMENT_PREPARATION_FAILED',
  BUILDER_SOURCE_CONFIG_REFUSED: 'ENVIRONMENT_PREPARATION_FAILED',
  BUILDER_SOURCE_INPUT_REFUSED: 'ENVIRONMENT_PREPARATION_FAILED',
  BUILDER_SOURCE_TREE_REFUSED: 'ENVIRONMENT_PREPARATION_FAILED',
  BUILDER_SANDBOX_COMMAND_INTERFACE_REQUIRED: 'ENVIRONMENT_PREPARATION_FAILED',
  BUILDER_SANDBOX_FRESH_CREATE_REQUIRED: 'ENVIRONMENT_PREPARATION_FAILED',
  BUILDER_SANDBOX_INCARNATION_CHANGED: 'ENVIRONMENT_PREPARATION_FAILED',
  BUILDER_STARTER_ENTRY_INSPECTION_FAILED: 'ENVIRONMENT_PREPARATION_FAILED',
  BUILDER_STARTER_ENTRY_UNSAFE: 'ENVIRONMENT_PREPARATION_FAILED',
  BUILDER_STARTER_ROOT_REFUSED: 'ENVIRONMENT_PREPARATION_FAILED',
  CONEXUS_APP_ROOT_MISSING: 'ENVIRONMENT_PREPARATION_FAILED',
  APPLICATION_COMPILER_SANDBOX_REFUSED: 'ENVIRONMENT_PREPARATION_FAILED',
  APPLICATION_COMPILER_WORKSPACE_REFUSED: 'ENVIRONMENT_PREPARATION_FAILED',

  BUILDER_MODEL_AUTH_FAILED: 'MODEL_CREDENTIAL_REFUSED',
  BUILDER_MODEL_CREDENTIAL_UNRESOLVABLE: 'MODEL_CREDENTIAL_REFUSED',
  MODEL_CONNECTION_REQUIRED: 'MODEL_CREDENTIAL_REFUSED',
  MODEL_CONNECTION_REVOKED: 'MODEL_CREDENTIAL_REFUSED',
  MODEL_AUTHORIZATION_REFUSED: 'MODEL_CREDENTIAL_REFUSED',
  CREDENTIAL_GENERATION_REFUSED: 'MODEL_CREDENTIAL_REFUSED',
  CREDENTIAL_REFRESH_RECONCILE_REQUIRED: 'MODEL_CREDENTIAL_REFUSED',
  MODEL_CONNECTION_PROVIDER_MISMATCH: 'MODEL_CREDENTIAL_REFUSED',

  BUILDER_MODEL_RATE_LIMITED: 'MODEL_RATE_LIMITED',

  BUILDER_MODEL_STREAM_FAILED: 'MODEL_REQUEST_REFUSED',
  BUILDER_AGENT_COMPLETION_UNAVAILABLE: 'MODEL_REQUEST_REFUSED',
  BUILDER_MODEL_INCOMPLETE: 'MODEL_REQUEST_REFUSED',
  BUILDER_MODEL_CHOICE_REFUSED: 'MODEL_REQUEST_REFUSED',
  BUILDER_MODEL_ADMISSION_REFUSED: 'MODEL_REQUEST_REFUSED',
  BUILDER_MESSAGE_ID_UNAVAILABLE: 'MODEL_REQUEST_REFUSED',
  PROJECT_MODEL_EGRESS_DENIED: 'MODEL_REQUEST_REFUSED',
  PROJECT_MODEL_ID_REFUSED: 'MODEL_REQUEST_REFUSED',
  PROJECT_MODEL_ORIGIN_INVALID: 'MODEL_REQUEST_REFUSED',
  PROJECT_MODEL_REDIRECT_DENIED: 'MODEL_REQUEST_REFUSED',
  PROJECT_MODEL_REQUEST_INVALID: 'MODEL_REQUEST_REFUSED',
  PROJECT_MODEL_RESPONSE_LIMIT_EXCEEDED: 'MODEL_REQUEST_REFUSED',
  PROJECT_MODEL_RESPONSE_LIMIT_INVALID: 'MODEL_REQUEST_REFUSED',

  BUILDER_RESULT_MATERIALIZATION_REFUSED: 'SOURCE_RESULT_REJECTED',
  BUILDER_RESULT_IDENTITY_REFUSED: 'SOURCE_RESULT_REJECTED',
  BUILDER_SOURCE_RESULT_INPUT_REFUSED: 'SOURCE_RESULT_REJECTED',
  BUILDER_SOURCE_RESULT_SANDBOX_REVISION_MISMATCH: 'SOURCE_RESULT_REJECTED',
  BUILDER_PLAN_SOURCE_RESULT_REFUSED: 'SOURCE_RESULT_REJECTED',
  BUILDER_RUNTIME_RESULT_SCOPE_REFUSED: 'SOURCE_RESULT_REJECTED',
  BUILDER_RUN_BASE_STALE: 'SOURCE_RESULT_REJECTED',

  APPLICATION_COMPILATION_FAILED: 'APPLICATION_BUILD_FAILED',
  APPLICATION_COMPILER_CONFIG_REFUSED: 'APPLICATION_BUILD_FAILED',
  APPLICATION_COMPILER_ENTRYPOINT_REFUSED: 'APPLICATION_BUILD_FAILED',
  APPLICATION_COMPILER_INPUT_LIMIT_REFUSED: 'APPLICATION_BUILD_FAILED',
  APPLICATION_COMPILER_INPUT_REFUSED: 'APPLICATION_BUILD_FAILED',
  APPLICATION_COMPILER_OUTPUT_ENTRYPOINT_REFUSED: 'APPLICATION_BUILD_FAILED',
  APPLICATION_COMPILER_OUTPUT_LIMIT_REFUSED: 'APPLICATION_BUILD_FAILED',
  APPLICATION_COMPILER_OUTPUT_MEDIA_TYPE_REFUSED: 'APPLICATION_BUILD_FAILED',
  APPLICATION_COMPILER_OUTPUT_PATH_REFUSED: 'APPLICATION_BUILD_FAILED',
  APPLICATION_COMPILER_OUTPUT_SIZE_REFUSED: 'APPLICATION_BUILD_FAILED',
  APPLICATION_COMPILER_RESULT_REFUSED: 'APPLICATION_BUILD_FAILED',
  APPLICATION_ENTRYPOINT_REFUSED: 'APPLICATION_BUILD_FAILED',
  APPLICATION_FILE_COUNT_REFUSED: 'APPLICATION_BUILD_FAILED',
  APPLICATION_FILE_DUPLICATE_REFUSED: 'APPLICATION_BUILD_FAILED',
  APPLICATION_FILE_ENCODING_REFUSED: 'APPLICATION_BUILD_FAILED',
  APPLICATION_FILE_HASH_REFUSED: 'APPLICATION_BUILD_FAILED',
  APPLICATION_FILE_ORDER_REFUSED: 'APPLICATION_BUILD_FAILED',
  APPLICATION_FILE_PATH_REFUSED: 'APPLICATION_BUILD_FAILED',
  APPLICATION_FILE_SHAPE_REFUSED: 'APPLICATION_BUILD_FAILED',
  APPLICATION_FILE_SIZE_REFUSED: 'APPLICATION_BUILD_FAILED',
  APPLICATION_MEDIA_TYPE_REFUSED: 'APPLICATION_BUILD_FAILED',
  APPLICATION_PAYLOAD_PIN_REFUSED: 'APPLICATION_BUILD_FAILED',
  APPLICATION_PAYLOAD_REFUSED: 'APPLICATION_BUILD_FAILED',
  APPLICATION_TOTAL_SIZE_REFUSED: 'APPLICATION_BUILD_FAILED',

  USER_CANCELLED: 'RUN_CANCELLED',
  HUB_RESTART: 'RUN_INTERRUPTED',
  BUILDER_RUN_CANCELLED: 'RUN_CANCELLED',
  APPLICATION_COMPILER_CANCELLED: 'RUN_CANCELLED',
  BUILDER_APPLICATION_CANCELLED: 'RUN_CANCELLED',
  BUILDER_LATE_RESULT_REFUSED: 'RUN_CANCELLED',

  // service.ts turns any error whose message is not an uppercase snake code into this one, so raw
  // E2B, Postgres and fetch faults arrive here. Calling it a preparation failure would name a cause
  // nobody established.
  BUILDER_PREPARATION_FAILED: 'INTERNAL_ERROR',
  BUILDER_RUN_INPUT_REFUSED: 'INTERNAL_ERROR',
  BUILDER_RUN_CREATE_FAILED: 'INTERNAL_ERROR',
  BUILDER_RUN_CLAIM_REFUSED: 'INTERNAL_ERROR',
  BUILDER_RUN_NOT_ADMITTED: 'INTERNAL_ERROR',
  BUILDER_RUN_ROW_INVALID: 'INTERNAL_ERROR',
  BUILDER_RUN_PHASE_UPDATE_REFUSED: 'INTERNAL_ERROR',
  BUILDER_RUN_MESSAGE_BIND_REFUSED: 'INTERNAL_ERROR',
  BUILDER_RUN_SANDBOX_BIND_REFUSED: 'INTERNAL_ERROR',
  BUILDER_RUN_SETTLEMENT_REFUSED: 'INTERNAL_ERROR',
  BUILDER_RUN_SOURCE_SETTLEMENT_REFUSED: 'INTERNAL_ERROR',
  BUILDER_RUN_BUILD_SETTLEMENT_REFUSED: 'INTERNAL_ERROR',
  BUILDER_RUN_FAILURE_REFUSED: 'INTERNAL_ERROR',
  BUILDER_RUN_INTERRUPTION_REFUSED: 'INTERNAL_ERROR',
  BUILDER_RUN_CANCELLATION_REFUSED: 'INTERNAL_ERROR',
})

// source.ts appends whatever code the git container reported, so these families have no closed
// member list. The category is known from the prefix; the code itself never reaches the wire.
const CATEGORY_BY_PREFIX: readonly (readonly [string, BuilderFailureCategory])[] = Object.freeze([
  ['BUILDER_SOURCE_BUNDLE_', 'ENVIRONMENT_PREPARATION_FAILED'],
  ['BUILDER_SOURCE_READ_', 'ENVIRONMENT_PREPARATION_FAILED'],
])

const declared = (code: string | null): boolean => code !== null && Object.hasOwn(CATEGORY_BY_CODE, code)

export const builderFailureCategory = (code: string | null): BuilderFailureCategory | null => {
  if (code === null) return null
  if (declared(code)) return CATEGORY_BY_CODE[code] as BuilderFailureCategory
  return CATEGORY_BY_PREFIX.find(([prefix]) => code.startsWith(prefix))?.[1] ?? 'INTERNAL_ERROR'
}

/** The one place a run becomes wire shape: an unmapped internal code never survives it. */
export const projectBuilderRun = (run: BuilderRunSummary): WireBuilderRun => Object.freeze({
  ...run,
  failureCategory: run.state === 'INTERRUPTED' && run.failureCode !== 'HUB_RESTART' ? 'RUN_CANCELLED' : builderFailureCategory(run.failureCode),
  failureCode: declared(run.failureCode) ? run.failureCode : null,
})
