-- Generated by gen-attacks.mjs. Each statement is expected to be REFUSED (SQLSTATE 42501 or
-- equivalent). BREACH means the statement succeeded and privilege separation failed.

DO $do$
BEGIN
  BEGIN
    EXECUTE $atk$select count(*) from p_b_preview.follow_up_note$atk$;
    RAISE NOTICE 'RESULT % BREACH % %', 'cross_select_b', 'n/a', 'statement succeeded';
  EXCEPTION WHEN OTHERS THEN
    RAISE NOTICE 'RESULT % REFUSED % %', 'cross_select_b', SQLSTATE, SQLERRM;
  END;
END
$do$;

DO $do$
BEGIN
  BEGIN
    EXECUTE $atk$set search_path to p_b_preview$atk$;
    RAISE NOTICE 'RESULT % BREACH % %', 'cross_search_path_b', 'n/a', 'statement succeeded';
  EXCEPTION WHEN OTHERS THEN
    RAISE NOTICE 'RESULT % REFUSED % %', 'cross_search_path_b', SQLSTATE, SQLERRM;
  END;
END
$do$;

DO $do$
BEGIN
  BEGIN
    EXECUTE $atk$set role p_b_runtime$atk$;
    RAISE NOTICE 'RESULT % BREACH % %', 'cross_set_role_b_runtime', 'n/a', 'statement succeeded';
  EXCEPTION WHEN OTHERS THEN
    RAISE NOTICE 'RESULT % REFUSED % %', 'cross_set_role_b_runtime', SQLSTATE, SQLERRM;
  END;
END
$do$;

DO $do$
BEGIN
  BEGIN
    EXECUTE $atk$set role p_b_migrator$atk$;
    RAISE NOTICE 'RESULT % BREACH % %', 'cross_set_role_b_migrator', 'n/a', 'statement succeeded';
  EXCEPTION WHEN OTHERS THEN
    RAISE NOTICE 'RESULT % REFUSED % %', 'cross_set_role_b_migrator', SQLSTATE, SQLERRM;
  END;
END
$do$;
