-- Generated by gen-attacks.mjs. Each statement is expected to be REFUSED (SQLSTATE 42501 or
-- equivalent). BREACH means the statement succeeded and privilege separation failed.

DO $do$
BEGIN
  BEGIN
    EXECUTE $atk$create extension if not exists dblink$atk$;
    RAISE NOTICE 'RESULT % BREACH % %', 'mig_create_extension', 'n/a', 'statement succeeded';
  EXCEPTION WHEN OTHERS THEN
    RAISE NOTICE 'RESULT % REFUSED % %', 'mig_create_extension', SQLSTATE, SQLERRM;
  END;
END
$do$;

DO $do$
BEGIN
  BEGIN
    EXECUTE $atk$create or replace function p_a_preview.esc() returns text language sql security definer as $body$ select current_user $body$$atk$;
    RAISE NOTICE 'RESULT % BREACH % %', 'mig_security_definer', 'n/a', 'statement succeeded';
  EXCEPTION WHEN OTHERS THEN
    RAISE NOTICE 'RESULT % REFUSED % %', 'mig_security_definer', SQLSTATE, SQLERRM;
  END;
END
$do$;

DO $do$
BEGIN
  BEGIN
    EXECUTE $atk$copy (select 1) to program 'id > /tmp/pwn'$atk$;
    RAISE NOTICE 'RESULT % BREACH % %', 'mig_copy_program', 'n/a', 'statement succeeded';
  EXCEPTION WHEN OTHERS THEN
    RAISE NOTICE 'RESULT % REFUSED % %', 'mig_copy_program', SQLSTATE, SQLERRM;
  END;
END
$do$;

DO $do$
BEGIN
  BEGIN
    EXECUTE $atk$alter role p_a_runtime superuser$atk$;
    RAISE NOTICE 'RESULT % BREACH % %', 'mig_alter_role', 'n/a', 'statement succeeded';
  EXCEPTION WHEN OTHERS THEN
    RAISE NOTICE 'RESULT % REFUSED % %', 'mig_alter_role', SQLSTATE, SQLERRM;
  END;
END
$do$;

DO $do$
BEGIN
  BEGIN
    EXECUTE $atk$grant usage on schema p_a_preview to p_b_runtime$atk$;
    RAISE NOTICE 'RESULT % BREACH % %', 'mig_grant_cross', 'n/a', 'statement succeeded';
  EXCEPTION WHEN OTHERS THEN
    RAISE NOTICE 'RESULT % REFUSED % %', 'mig_grant_cross', SQLSTATE, SQLERRM;
  END;
END
$do$;

DO $do$
BEGIN
  BEGIN
    EXECUTE $atk$create schema evil authorization p_a_migrator$atk$;
    RAISE NOTICE 'RESULT % BREACH % %', 'mig_create_schema_foreign', 'n/a', 'statement succeeded';
  EXCEPTION WHEN OTHERS THEN
    RAISE NOTICE 'RESULT % REFUSED % %', 'mig_create_schema_foreign', SQLSTATE, SQLERRM;
  END;
END
$do$;

DO $do$
BEGIN
  BEGIN
    EXECUTE $atk$create extension if not exists postgres_fdw$atk$;
    RAISE NOTICE 'RESULT % BREACH % %', 'mig_read_hub_fdw', 'n/a', 'statement succeeded';
  EXCEPTION WHEN OTHERS THEN
    RAISE NOTICE 'RESULT % REFUSED % %', 'mig_read_hub_fdw', SQLSTATE, SQLERRM;
  END;
END
$do$;

DO $do$
BEGIN
  BEGIN
    EXECUTE $atk$update pg_authid set rolsuper=true where rolname='p_a_migrator'$atk$;
    RAISE NOTICE 'RESULT % BREACH % %', 'mig_write_pg_catalog', 'n/a', 'statement succeeded';
  EXCEPTION WHEN OTHERS THEN
    RAISE NOTICE 'RESULT % REFUSED % %', 'mig_write_pg_catalog', SQLSTATE, SQLERRM;
  END;
END
$do$;
