// Generates attacks-migration.sql and attacks-cross-project.sql from the same attack list as the
// Q1 arena (spike/q1-runner/adversarial/migrations.mjs and cross_project_sql.mjs on
// origin/spike/q1-runner-arena), wrapped so each statement's outcome (BREACH or the exact
// SQLSTATE Postgres refused it with) is captured uniformly via RAISE NOTICE instead of relying on
// psql's own nonzero-exit behavior (a DO block swallows the error, so the script always
// completes and the notices carry the verdict).
//
// The two files must run under different roles, matching the arena: MIGRATION_ATTACKS as
// p_a_migrator (schema owner, not superuser), CROSS_PROJECT_ATTACKS as p_a_runtime (the Project A
// runtime role probing for Project B).
import { writeFileSync } from 'node:fs'

// Copied verbatim from adversarial/migrations.mjs. Run as p_a_migrator against conexus_apps.
const MIGRATION_ATTACKS = [
  { id: 'mig_create_extension', sql: 'create extension if not exists dblink' },
  { id: 'mig_security_definer', sql: "create or replace function p_a_preview.esc() returns text language sql security definer as $body$ select current_user $body$" },
  { id: 'mig_copy_program', sql: "copy (select 1) to program 'id > /tmp/pwn'" },
  { id: 'mig_alter_role', sql: 'alter role p_a_runtime superuser' },
  { id: 'mig_grant_cross', sql: 'grant usage on schema p_a_preview to p_b_runtime' },
  { id: 'mig_create_schema_foreign', sql: 'create schema evil authorization p_a_migrator' },
  { id: 'mig_read_hub_fdw', sql: 'create extension if not exists postgres_fdw' },
  { id: 'mig_write_pg_catalog', sql: "update pg_authid set rolsuper=true where rolname='p_a_migrator'" },
]

// Copied from adversarial/cross_project_sql.mjs. Run as p_a_runtime against conexus_apps.
const CROSS_PROJECT_ATTACKS = [
  { id: 'cross_select_b', sql: 'select count(*) from p_b_preview.follow_up_note' },
  { id: 'cross_search_path_b', sql: 'set search_path to p_b_preview' },
  { id: 'cross_set_role_b_runtime', sql: 'set role p_b_runtime' },
  { id: 'cross_set_role_b_migrator', sql: 'set role p_b_migrator' },
]

// EXECUTE needs a SQL string literal, not a JS-style double-quoted string (which Postgres parses
// as an identifier and fails with 42703 "column does not exist" before the attack's own privilege
// check ever runs). Dollar-quote the attack SQL with a tag distinct from the ones the attacks
// themselves use internally (mig_security_definer's function body already uses $body$).
const block = ({ id, sql }) => `DO $do$
BEGIN
  BEGIN
    EXECUTE $atk$${sql}$atk$;
    RAISE NOTICE 'RESULT % BREACH % %', '${id}', 'n/a', 'statement succeeded';
  EXCEPTION WHEN OTHERS THEN
    RAISE NOTICE 'RESULT % REFUSED % %', '${id}', SQLSTATE, SQLERRM;
  END;
END
$do$;`

const header = [
  '-- Generated by gen-attacks.mjs. Each statement is expected to be REFUSED (SQLSTATE 42501 or',
  '-- equivalent). BREACH means the statement succeeded and privilege separation failed.',
].join('\n')

writeFileSync('./attacks-migration.sql', `${header}\n\n${MIGRATION_ATTACKS.map(block).join('\n\n')}\n`)
writeFileSync('./attacks-cross-project.sql', `${header}\n\n${CROSS_PROJECT_ATTACKS.map(block).join('\n\n')}\n`)
console.log(`wrote attacks-migration.sql (${MIGRATION_ATTACKS.length} attacks), attacks-cross-project.sql (${CROSS_PROJECT_ATTACKS.length} attacks)`)
