import assert from 'node:assert/strict'
import { spawnSync } from 'node:child_process'
import { mkdirSync, mkdtempSync, rmSync, symlinkSync, writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { dirname, join, resolve } from 'node:path'
import { pathToFileURL } from 'node:url'
import test from 'node:test'
import ts from 'typescript'
import { ensureCompilerRoot } from './compiler-root.mjs'
import { generateClient } from '../../apps/hub/compiler-template/generate-client.mjs'
import { readFailures, renderAppFailuresSource } from '../../scripts/generate-failures.mjs'

const repositoryRoot = resolve(import.meta.dirname, '../..')
const string = (extra = {}) => ({ type: 'string', ...extra })
const MANIFEST = {
  operations: {
    listItems: {
      handler: 'handlers/items.ts',
      export: 'listItems',
      input: { type: 'object', properties: { category: string({ minLength: 1, maxLength: 80 }), page: { type: 'integer', minimum: 1 }, active: { type: 'boolean' } }, required: ['category'], additionalProperties: false },
      output: { type: 'array', maxItems: 500, items: { type: 'object', properties: { id: { type: 'integer' }, name: string(), price: { type: 'number', minimum: 0, maximum: 1000000 }, note: string({ maxLength: 200 }) }, required: ['id', 'name', 'price'], additionalProperties: false } },
    },
    addItem: {
      handler: 'handlers/items.ts',
      export: 'addItem',
      input: { type: 'object', properties: { name: string({ minLength: 2 }) }, required: ['name'], additionalProperties: false },
      output: { type: 'object', properties: { id: { type: 'integer' }, tags: { type: 'array', items: string() } }, required: ['id'], additionalProperties: false },
    },
  },
}

const EXPECTED_API = `// Generated by Conexus from conexus/manifest.json. Every check and build rewrites this file; do not edit it.
import { z } from 'zod'
import { ConexusError } from './failures.gen'

export const schemas = {
  addItem: {
    input: z.strictObject({ name: z.string().min(2) }),
    output: z.strictObject({ id: z.number().int(), tags: z.array(z.string()).optional() }),
  },
  listItems: {
    input: z.strictObject({ category: z.string().min(1).max(80), page: z.number().int().min(1).optional(), active: z.boolean().optional() }),
    output: z.array(z.strictObject({ id: z.number().int(), name: z.string(), price: z.number().min(0).max(1000000), note: z.string().max(200).optional() })).max(500),
  },
} as const

export type OperationId = keyof typeof schemas
export type Input<K extends OperationId> = z.infer<(typeof schemas)[K]['input']>
export type Output<K extends OperationId> = z.infer<(typeof schemas)[K]['output']>

const failure = (status: number, body: string): ConexusError => {
  try {
    const parsed: unknown = JSON.parse(body)
    if (typeof parsed === 'object' && parsed !== null) {
      const { code, detail } = parsed as { code?: unknown; detail?: unknown }
      if (typeof code === 'string') return new ConexusError(code, typeof detail === 'string' ? detail : '')
    }
  } catch {}
  return new ConexusError(\`HTTP_\${status}\`, body.slice(0, 500))
}

const call = async <K extends OperationId>(id: K, input: Input<K>): Promise<Output<K>> => {
  const response = await fetch(\`/__conexus/api/\${id}\`, {
    method: 'POST',
    headers: { 'content-type': 'application/json' },
    body: JSON.stringify(input),
  })
  const body = await response.text()
  if (!response.ok) throw failure(response.status, body)
  return JSON.parse(body) as Output<K>
}

export const api = {
  addItem: (input: Input<'addItem'>) => call('addItem', input),
  listItems: (input: Input<'listItems'>) => call('listItems', input),
} as const
`

const EXPECTED_TYPES = `// Generated by Conexus from conexus/manifest.json. Every check and build rewrites this file; do not edit it.
export type Operations = {
  addItem: { input: { name: string }; output: { id: number; tags?: readonly string[] } }
  listItems: { input: { category: string; page?: number; active?: boolean }; output: readonly { id: number; name: string; price: number; note?: string }[] }
}

export type OperationId = keyof Operations
export type Input<K extends OperationId> = Operations[K]['input']
export type Output<K extends OperationId> = Operations[K]['output']
`

test('every schema construct maps to its zod and TypeScript form, with operations in sorted id order', () => {
  const { apiGen, typesGen } = generateClient(MANIFEST)
  assert.equal(apiGen, EXPECTED_API)
  assert.equal(typesGen, EXPECTED_TYPES)
})

test('a string enum generates a zod enum and a TypeScript union, also inside an array', () => {
  const status = { type: 'string', enum: ['open', 'closed'] }
  const manifest = { operations: { setStatus: { handler: 'handlers/a.ts', export: 'setStatus', input: { type: 'object', properties: { status, all: { type: 'array', items: status } }, required: ['status'], additionalProperties: false }, output: status } } }
  const { apiGen, typesGen } = generateClient(manifest)
  assert.match(apiGen, /^ {4}input: z\.strictObject\(\{ status: z\.enum\(\["open", "closed"\]\), all: z\.array\(z\.enum\(\["open", "closed"\]\)\)\.optional\(\) \}\),\n {4}output: z\.enum\(\["open", "closed"\]\),$/m)
  assert.match(typesGen, /^ {2}setStatus: \{ input: \{ status: "open" \| "closed"; all\?: readonly \("open" \| "closed"\)\[\] \}; output: "open" \| "closed" \}$/m)
})

test('an unsatisfiable bound is refused with the place it is in', () => {
  const bad = (schema) => () => generateClient({ operations: { find: { handler: 'handlers/a.ts', export: 'find', input: { type: 'object', properties: { q: schema }, additionalProperties: false }, output: { type: 'boolean' } } } })
  assert.throws(bad({ type: 'string', minLength: 5, maxLength: 2 }), { message: 'MANIFEST_REFUSED: operations.find.input.properties.q: "minLength" is above "maxLength"' })
  assert.throws(bad({ type: 'number', minimum: 10, maximum: 1 }), { message: 'MANIFEST_REFUSED: operations.find.input.properties.q: "minimum" is above "maximum"' })
  assert.doesNotThrow(bad({ type: 'integer', minimum: 3, maximum: 3 }))
})

const scratch = mkdtempSync(join(resolve(repositoryRoot, 'node_modules/.cache'), 'client-gen-'))
const transpile = (source) => ts.transpileModule(source, { compilerOptions: { module: ts.ModuleKind.ESNext, target: ts.ScriptTarget.ES2022 } }).outputText
const FAILURES_GEN = renderAppFailuresSource(readFailures())
writeFileSync(join(scratch, 'failures.gen.mjs'), transpile(FAILURES_GEN))
const compile = (source, name) => {
  const file = join(scratch, name)
  writeFileSync(file, transpile(source).replace("'./failures.gen'", "'./failures.gen.mjs'"))
  return import(pathToFileURL(file).href)
}

const withFetch = async (answer, run) => {
  const original = globalThis.fetch
  const calls = []
  globalThis.fetch = async (url, init) => {
    calls.push({ url, init })
    return new Response(answer.body, { status: answer.status })
  }
  try {
    return await run(calls)
  } finally {
    globalThis.fetch = original
  }
}

test('api.<operation> posts the input as JSON and answers the parsed body', async () => {
  const { api } = await compile(generateClient(MANIFEST).apiGen, 'ok.mjs')
  await withFetch({ status: 200, body: '[{"id":1,"name":"a","price":2}]' }, async (calls) => {
    assert.deepEqual(await api.listItems({ category: 'x' }), [{ id: 1, name: 'a', price: 2 }])
    assert.deepEqual(calls, [{ url: '/__conexus/api/listItems', init: { method: 'POST', headers: { 'content-type': 'application/json' }, body: '{"category":"x"}' } }])
  })
})

test('a non 2xx answer throws ConexusError with the code and detail of the JSON error body', async () => {
  const { api } = await compile(generateClient(MANIFEST).apiGen, 'json-error.mjs')
  const { ConexusError } = await import(pathToFileURL(join(scratch, 'failures.gen.mjs')).href)
  await withFetch({ status: 422, body: '{"code":"INPUT_REFUSED","detail":"/category: too short"}' }, async () => {
    const error = await api.addItem({ name: 'ab' }).catch((thrown) => thrown)
    assert.equal(error instanceof ConexusError, true)
    assert.deepEqual([error.name, error.code, error.detail, error.message], ['ConexusError', 'INPUT_REFUSED', '/category: too short', 'INPUT_REFUSED: /category: too short'])
  })
  await withFetch({ status: 422, body: '{"code":"HANDLER_FAILED"}' }, async () => {
    const error = await api.addItem({ name: 'ab' }).catch((thrown) => thrown)
    assert.deepEqual([error.code, error.detail, error.message], ['HANDLER_FAILED', '', 'HANDLER_FAILED'])
  })
})

test('a non 2xx answer that is not the runner error JSON throws HTTP_<status> with the first 500 characters', async () => {
  const { api } = await compile(generateClient(MANIFEST).apiGen, 'text-error.mjs')
  const long = `<html>${'x'.repeat(600)}`
  await withFetch({ status: 502, body: long }, async () => {
    const error = await api.addItem({ name: 'ab' }).catch((thrown) => thrown)
    assert.deepEqual([error.code, error.detail], ['HTTP_502', long.slice(0, 500)])
    assert.equal(error.detail.length, 500)
  })
  for (const body of ['{"unexpected":true}', '{"error":{"code":"INPUT_REFUSED"}}', '{"code":5}', 'null']) {
    await withFetch({ status: 500, body }, async () => {
      const error = await api.addItem({ name: 'ab' }).catch((thrown) => thrown)
      assert.deepEqual([error.code, error.detail], ['HTTP_500', body])
    })
  }
})

test('the generated schemas refuse what the manifest bounds refuse', async () => {
  const { schemas } = await compile(generateClient(MANIFEST).apiGen, 'schemas.mjs')
  const input = schemas.listItems.input
  assert.equal(input.safeParse({ category: 'a' }).success, true)
  assert.equal(input.safeParse({ category: '' }).success, false)
  assert.equal(input.safeParse({ category: 'a'.repeat(81) }).success, false)
  assert.equal(input.safeParse({ category: 'a', page: 0 }).success, false)
  assert.equal(input.safeParse({ category: 'a', page: 1.5 }).success, false)
  assert.equal(input.safeParse({ category: 'a', extra: 1 }).success, false)
  assert.equal(schemas.listItems.output.safeParse(Array.from({ length: 501 }, () => ({ id: 1, name: 'a', price: 1 }))).success, false)
})

const compilerRoot = await ensureCompilerRoot()
const { typescriptProjects } = await import(join(compilerRoot, 'tsconfig.mjs'))

const checkout = (manifest, files) => {
  const root = mkdtempSync(join(tmpdir(), 'conexus-client-'))
  const { apiGen, typesGen } = generateClient(manifest)
  for (const [path, content] of Object.entries({ 'app/src/conexus/api.gen.ts': apiGen, 'conexus/types.gen.ts': typesGen, 'app/src/conexus/failures.gen.ts': FAILURES_GEN, ...files })) {
    mkdirSync(dirname(join(root, path)), { recursive: true })
    writeFileSync(join(root, path), content)
  }
  symlinkSync(join(compilerRoot, 'node_modules'), join(root, 'app/node_modules'))
  return root
}

const typecheck = (root, project) => {
  const config = join(root, `tsconfig.${project}.json`)
  writeFileSync(config, JSON.stringify(typescriptProjects({ compilerRoot, root })[project]))
  const result = spawnSync(process.execPath, [join(compilerRoot, 'node_modules/typescript/bin/tsc'), '-p', config, '--pretty', 'false'], { encoding: 'utf8', cwd: root })
  return { status: result.status, output: `${result.stdout}${result.stderr}` }
}

const SCREEN = `import { useQuery } from '@tanstack/react-query'
import { api } from '@/conexus/api.gen'

export function Names() {
  const { data } = useQuery({ queryKey: ['listItems', { category: 'a' }], queryFn: () => api.listItems({ category: 'a' }) })
  return <ul>{data?.map((item) => <li key={item.id}>{item.name}</li>)}</ul>
}
`

const HANDLER = `import type { Input, Output } from '../types.gen'

export async function addItem(input: Input<'addItem'>): Promise<Output<'addItem'>> {
  return { id: input.name.length }
}
`

test('a screen and a handler written against the manifest typecheck', () => {
  const root = checkout(MANIFEST, { 'app/src/names.tsx': SCREEN, 'conexus/handlers/items.ts': HANDLER })
  try {
    assert.deepEqual(typecheck(root, 'app'), { status: 0, output: '' })
    assert.deepEqual(typecheck(root, 'server'), { status: 0, output: '' })
  } finally {
    rmSync(root, { recursive: true, force: true })
  }
})

test('renaming an output field in the manifest fails the screen and the handler that read the old one, by file and line', () => {
  const renamed = structuredClone(MANIFEST)
  renamed.operations.listItems.output.items.properties = { id: { type: 'integer' }, title: string(), price: { type: 'number' } }
  renamed.operations.listItems.output.items.required = ['id', 'title', 'price']
  renamed.operations.addItem.output.properties = { key: { type: 'integer' } }
  renamed.operations.addItem.output.required = ['key']
  const root = checkout(renamed, { 'app/src/names.tsx': SCREEN, 'conexus/handlers/items.ts': HANDLER })
  try {
    const screen = typecheck(root, 'app')
    assert.equal(screen.status, 2)
    assert.match(screen.output, /^app\/src\/names\.tsx\(6,\d+\): error TS2339: Property 'name' does not exist on type/m)
    const handler = typecheck(root, 'server')
    assert.equal(handler.status, 2)
    assert.match(handler.output, /^conexus\/handlers\/items\.ts\(4,\d+\): error TS2353: Object literal may only specify known properties, and 'id' does not exist in type/m)
  } finally {
    rmSync(root, { recursive: true, force: true })
  }
})

test('a manifest with no operations still generates two files that typecheck', () => {
  const root = checkout({ operations: {} }, {})
  try {
    assert.deepEqual(typecheck(root, 'app'), { status: 0, output: '' })
    assert.deepEqual(typecheck(root, 'server'), { status: 0, output: '' })
  } finally {
    rmSync(root, { recursive: true, force: true })
  }
})

test('types.gen.ts has no imports, so a handler that imports it stays inside conexus/', () => {
  assert.doesNotMatch(generateClient(MANIFEST).typesGen, /^import /m)
})

test.after(() => rmSync(scratch, { recursive: true, force: true }))
