import { readFileSync, readdirSync, writeFileSync } from 'node:fs'
import { join, relative, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { buildReplay } from './generate-hub-catalog-snapshot.mjs'
import { hubSources, stripComments } from './hub-sources.mjs'

const repo = resolve(fileURLToPath(new URL('../', import.meta.url)))
const outputPath = join(repo, 'docs/reference/function-callers.md')
const migrationsDir = join(repo, 'apps/hub/migrations')

const escapeRegExp = (text) => text.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')
const callOf = (name) => new RegExp(`(?<![\\w.])${escapeRegExp(name)}\\s*\\(`, 'i')

const createdNames = () => new Set(readdirSync(migrationsDir).filter((file) => file.endsWith('.sql')).flatMap((file) =>
  [...stripComments(readFileSync(join(migrationsDir, file), 'utf8')).matchAll(/\bCREATE\s+(?:OR\s+REPLACE\s+)?FUNCTION\s+([a-z_]+\.[a-z_0-9]+)\s*\(/gi)].map((match) => match[1].toLowerCase())))

export const graph = (functions, sources, created) => {
  const live = [...new Set(functions.map((fn) => fn.name))]
  const edges = []
  for (const fn of functions) {
    for (const name of live) if (name !== fn.name && callOf(name).test(fn.body)) edges.push({ callee: name, caller: fn.name, side: 'sql' })
  }
  for (const source of sources) {
    for (const name of live) if (callOf(name).test(source.text)) edges.push({ callee: name, caller: source.path, side: 'typescript' })
  }
  const dangling = []
  for (const name of [...created].filter((candidate) => !live.includes(candidate))) {
    for (const fn of functions) if (callOf(name).test(fn.body)) dangling.push(`${fn.name} calls the dropped ${name}`)
    for (const source of sources) if (callOf(name).test(source.text)) dangling.push(`${source.path} calls the dropped ${name}`)
  }
  return { live, edges, dangling }
}

export const render = (functions, { live, edges }) => {
  const ownerOf = new Map(functions.map((fn) => [fn.name, fn.owner]))
  const sqlCallers = (name) => [...new Set(edges.filter((edge) => edge.callee === name && edge.side === 'sql').map((edge) => `\`${edge.caller}\``))].sort()
  const tsCallers = (name) => [...new Set(edges.filter((edge) => edge.callee === name && edge.side === 'typescript').map((edge) => `\`${edge.caller}\``))].sort()
  const rows = live.map((name) => `| \`${name}\` | ${ownerOf.get(name)} | ${sqlCallers(name).join(', ') || '-'} | ${tsCallers(name).join(', ') || '-'} |`)
  const schemaOf = (name) => name.split('.')[0]
  const crossing = edges.filter((edge) => edge.side === 'sql' && schemaOf(edge.callee) !== schemaOf(edge.caller))
    .map((edge) => `- \`${edge.caller}\` calls \`${edge.callee}\``).sort()
  return `# Hub function callers

Generated by \`npm run db:callers\` from the migrations replayed into a scratch database, the live function bodies and the SQL text in \`apps/hub/src\`. Do not edit by hand; \`npm run db:callers:check\` fails when it differs, and fails while a function a migration dropped is still called.

A part that ports an owner reads its functions here: a function with a caller in another owner's body cannot be dropped until that caller is ported.

## Calls across schemas

${crossing.join('\n') || 'None.'}

## Every live function

| Function | Owner role | Called by functions | Called from TypeScript |
| --- | --- | --- | --- |
${rows.join('\n')}
`
}

const isEntrypoint = process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)
if (isEntrypoint) {
  const { functions } = await buildReplay()
  const built = graph(functions, hubSources(), createdNames())
  if (built.dangling.length > 0) {
    console.error(`function-callers: ${built.dangling.join('; ')}`)
    process.exit(1)
  }
  const text = render(functions, built)
  if (process.argv.includes('--check')) {
    if (readFileSync(outputPath, 'utf8') !== text) {
      console.error(`function-callers: ${relative(repo, outputPath)} is out of date; run npm run db:callers`)
      process.exit(1)
    }
    console.log(`function-callers: ${built.live.length} functions, ${built.edges.length} edges, current`)
  } else {
    writeFileSync(outputPath, text)
    console.log(`function-callers: wrote ${built.live.length} functions, ${built.edges.length} edges`)
  }
}
