import { mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { pathToFileURL } from 'node:url'

/** Where the two generated files live in a checkout. Neither is ever committed. */
export const API_GEN_PATH = 'app/src/conexus/api.gen.ts'
export const TYPES_GEN_PATH = 'conexus/types.gen.ts'

const HEADER = '// Generated by Conexus from conexus/manifest.json. Every check and build rewrites this file; do not edit it.\n'

const refuse = (where, why) => {
  throw new Error(`MANIFEST_REFUSED: ${where}: ${why}`)
}

const boundsInOrder = (schema, where) => {
  const [low, high] = schema.type === 'string' ? ['minLength', 'maxLength'] : ['minimum', 'maximum']
  if (schema[low] !== undefined && schema[high] !== undefined && schema[low] > schema[high]) refuse(where, `"${low}" is above "${high}"`)
}

const zodOf = (schema, where) => {
  switch (schema.type) {
    case 'string':
      if (schema.enum !== undefined) return `z.enum([${schema.enum.map((value) => JSON.stringify(value)).join(', ')}])`
      boundsInOrder(schema, where)
      return `z.string()${schema.minLength === undefined ? '' : `.min(${schema.minLength})`}${schema.maxLength === undefined ? '' : `.max(${schema.maxLength})`}`
    case 'integer':
    case 'number':
      boundsInOrder(schema, where)
      return `z.number()${schema.type === 'integer' ? '.int()' : ''}${schema.minimum === undefined ? '' : `.min(${schema.minimum})`}${schema.maximum === undefined ? '' : `.max(${schema.maximum})`}`
    case 'boolean':
      return 'z.boolean()'
    case 'object': {
      const required = new Set(schema.required ?? [])
      const fields = Object.entries(schema.properties).map(([name, property]) => `${name}: ${zodOf(property, `${where}.properties.${name}`)}${required.has(name) ? '' : '.optional()'}`)
      return `z.strictObject({ ${fields.join(', ')} })`
    }
    case 'array':
      return `z.array(${zodOf(schema.items, `${where}.items`)})${schema.maxItems === undefined ? '' : `.max(${schema.maxItems})`}`
    default:
      return refuse(where, `unknown type "${schema.type}"`)
  }
}

const typeOf = (schema) => {
  switch (schema.type) {
    case 'string':
      return schema.enum === undefined ? 'string' : schema.enum.map((value) => JSON.stringify(value)).join(' | ')
    case 'integer':
    case 'number':
      return 'number'
    case 'boolean':
      return 'boolean'
    case 'object': {
      const required = new Set(schema.required ?? [])
      const fields = Object.entries(schema.properties).map(([name, property]) => `${name}${required.has(name) ? '' : '?'}: ${typeOf(property)}`)
      return fields.length === 0 ? '{}' : `{ ${fields.join('; ')} }`
    }
    case 'array':
      return `readonly ${schema.items.enum === undefined ? typeOf(schema.items) : `(${typeOf(schema.items)})`}[]`
    default:
      return refuse('schema', `unknown type "${schema.type}"`)
  }
}

const ERROR_AND_CALL = `const failure = (status: number, body: string): ConexusError => {
  try {
    const parsed: unknown = JSON.parse(body)
    if (typeof parsed === 'object' && parsed !== null) {
      const { code, detail } = parsed as { code?: unknown; detail?: unknown }
      if (typeof code === 'string') return new ConexusError(code, typeof detail === 'string' ? detail : '')
    }
  } catch {}
  return new ConexusError(\`HTTP_\${status}\`, body.slice(0, 500))
}

const call = async <K extends OperationId>(id: K, input: Input<K>): Promise<Output<K>> => {
  const response = await fetch(\`/__conexus/api/\${id}\`, {
    method: 'POST',
    headers: { 'content-type': 'application/json' },
    body: JSON.stringify(input),
  })
  const body = await response.text()
  if (!response.ok) throw failure(response.status, body)
  return JSON.parse(body) as Output<K>
}
`

/**
 * The typed client of one manifest: `apiGen` for `app/src/conexus/api.gen.ts` (zod schemas with the
 * manifest's bounds, `Input<K>`, `Output<K>` and `api.<operation>(input)`) and `typesGen` for
 * `conexus/types.gen.ts` (the same types as plain declarations with no imports, for handlers).
 * Operations come out in sorted id order. The manifest is the admitted `conexus/manifest.json`.
 */
export const generateClient = (manifest) => {
  const ids = Object.keys(manifest.operations).sort()
  const schemas = ids.map((id) => {
    const { input, output } = manifest.operations[id]
    return `  ${id}: {\n    input: ${zodOf(input, `operations.${id}.input`)},\n    output: ${zodOf(output, `operations.${id}.output`)},\n  },`
  })
  const operations = ids.map((id) => {
    const { input, output } = manifest.operations[id]
    return `  ${id}: { input: ${typeOf(input)}; output: ${typeOf(output)} }`
  })
  const apiGen = `${HEADER}import { z } from 'zod'
import { ConexusError } from './failures.gen'

export const schemas = {
${schemas.join('\n')}
} as const

export type OperationId = keyof typeof schemas
export type Input<K extends OperationId> = z.infer<(typeof schemas)[K]['input']>
export type Output<K extends OperationId> = z.infer<(typeof schemas)[K]['output']>

${ERROR_AND_CALL}
export const api = {
${ids.map((id) => `  ${id}: (input: Input<'${id}'>) => call('${id}', input),`).join('\n')}
} as const
`
  const typesGen = `${HEADER}export type Operations = {
${operations.join('\n')}
}

export type OperationId = keyof Operations
export type Input<K extends OperationId> = Operations[K]['input']
export type Output<K extends OperationId> = Operations[K]['output']
`
  return Object.freeze({ apiGen, typesGen })
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  const root = process.argv[2]
  if (!root) throw new Error('USAGE: node generate-client.mjs <checkout root>')
  const { apiGen, typesGen } = generateClient(JSON.parse(readFileSync(join(root, 'conexus/manifest.json'), 'utf8')))
  for (const [path, content] of [[API_GEN_PATH, apiGen], [TYPES_GEN_PATH, typesGen]]) {
    mkdirSync(dirname(join(root, path)), { recursive: true })
    writeFileSync(join(root, path), content)
  }
}
